// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Budget is the predicate function for budget builders.
type Budget func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// ChatMessage is the predicate function for chatmessage builders.
type ChatMessage func(*sql.Selector)

// Expense is the predicate function for expense builders.
type Expense func(*sql.Selector)

// RecurringExpense is the predicate function for recurringexpense builders.
type RecurringExpense func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
