// Code generated by ent, DO NOT EDIT.

package user

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPasswordHash holds the string denoting the password_hash field in the database.
	FieldPasswordHash = "password_hash"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLastName holds the string denoting the last_name field in the database.
	FieldLastName = "last_name"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldTheme holds the string denoting the theme field in the database.
	FieldTheme = "theme"
	// FieldWeeklyStart holds the string denoting the weekly_start field in the database.
	FieldWeeklyStart = "weekly_start"
	// FieldMonthlyStartDay holds the string denoting the monthly_start_day field in the database.
	FieldMonthlyStartDay = "monthly_start_day"
	// FieldBudgetAlertThreshold holds the string denoting the budget_alert_threshold field in the database.
	FieldBudgetAlertThreshold = "budget_alert_threshold"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// EdgeCategories holds the string denoting the categories edge name in mutations.
	EdgeCategories = "categories"
	// EdgeExpenses holds the string denoting the expenses edge name in mutations.
	EdgeExpenses = "expenses"
	// EdgeBudgets holds the string denoting the budgets edge name in mutations.
	EdgeBudgets = "budgets"
	// EdgeRecurringExpenses holds the string denoting the recurring_expenses edge name in mutations.
	EdgeRecurringExpenses = "recurring_expenses"
	// EdgeChatMessages holds the string denoting the chat_messages edge name in mutations.
	EdgeChatMessages = "chat_messages"
	// Table holds the table name of the user in the database.
	Table = "users"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "sessions"
	// SessionsInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionsInverseTable = "sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "user_id"
	// CategoriesTable is the table that holds the categories relation/edge.
	CategoriesTable = "categories"
	// CategoriesInverseTable is the table name for the Category entity.
	// It exists in this package in order to avoid circular dependency with the "category" package.
	CategoriesInverseTable = "categories"
	// CategoriesColumn is the table column denoting the categories relation/edge.
	CategoriesColumn = "user_id"
	// ExpensesTable is the table that holds the expenses relation/edge.
	ExpensesTable = "expenses"
	// ExpensesInverseTable is the table name for the Expense entity.
	// It exists in this package in order to avoid circular dependency with the "expense" package.
	ExpensesInverseTable = "expenses"
	// ExpensesColumn is the table column denoting the expenses relation/edge.
	ExpensesColumn = "user_id"
	// BudgetsTable is the table that holds the budgets relation/edge.
	BudgetsTable = "budgets"
	// BudgetsInverseTable is the table name for the Budget entity.
	// It exists in this package in order to avoid circular dependency with the "budget" package.
	BudgetsInverseTable = "budgets"
	// BudgetsColumn is the table column denoting the budgets relation/edge.
	BudgetsColumn = "user_id"
	// RecurringExpensesTable is the table that holds the recurring_expenses relation/edge.
	RecurringExpensesTable = "recurring_expenses"
	// RecurringExpensesInverseTable is the table name for the RecurringExpense entity.
	// It exists in this package in order to avoid circular dependency with the "recurringexpense" package.
	RecurringExpensesInverseTable = "recurring_expenses"
	// RecurringExpensesColumn is the table column denoting the recurring_expenses relation/edge.
	RecurringExpensesColumn = "user_id"
	// ChatMessagesTable is the table that holds the chat_messages relation/edge.
	ChatMessagesTable = "chat_messages"
	// ChatMessagesInverseTable is the table name for the ChatMessage entity.
	// It exists in this package in order to avoid circular dependency with the "chatmessage" package.
	ChatMessagesInverseTable = "chat_messages"
	// ChatMessagesColumn is the table column denoting the chat_messages relation/edge.
	ChatMessagesColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldUsername,
	FieldPasswordHash,
	FieldEmail,
	FieldFirstName,
	FieldLastName,
	FieldCurrency,
	FieldTheme,
	FieldWeeklyStart,
	FieldMonthlyStartDay,
	FieldBudgetAlertThreshold,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	PasswordHashValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultTheme holds the default value on creation for the "theme" field.
	DefaultTheme string
	// DefaultWeeklyStart holds the default value on creation for the "weekly_start" field.
	DefaultWeeklyStart string
	// DefaultMonthlyStartDay holds the default value on creation for the "monthly_start_day" field.
	DefaultMonthlyStartDay int
	// DefaultBudgetAlertThreshold holds the default value on creation for the "budget_alert_threshold" field.
	DefaultBudgetAlertThreshold float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPasswordHash orders the results by the password_hash field.
func ByPasswordHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPasswordHash, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByFirstName orders the results by the first_name field.
func ByFirstName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstName, opts...).ToFunc()
}

// ByLastName orders the results by the last_name field.
func ByLastName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastName, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByTheme orders the results by the theme field.
func ByTheme(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTheme, opts...).ToFunc()
}

// ByWeeklyStart orders the results by the weekly_start field.
func ByWeeklyStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyStart, opts...).ToFunc()
}

// ByMonthlyStartDay orders the results by the monthly_start_day field.
func ByMonthlyStartDay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyStartDay, opts...).ToFunc()
}

// ByBudgetAlertThreshold orders the results by the budget_alert_threshold field.
func ByBudgetAlertThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBudgetAlertThreshold, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// BySessionsCount orders the results by sessions count.
func BySessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionsStep(), opts...)
	}
}

// BySessions orders the results by sessions terms.
func BySessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCategoriesCount orders the results by categories count.
func ByCategoriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCategoriesStep(), opts...)
	}
}

// ByCategories orders the results by categories terms.
func ByCategories(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCategoriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByExpensesCount orders the results by expenses count.
func ByExpensesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newExpensesStep(), opts...)
	}
}

// ByExpenses orders the results by expenses terms.
func ByExpenses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newExpensesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBudgetsCount orders the results by budgets count.
func ByBudgetsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBudgetsStep(), opts...)
	}
}

// ByBudgets orders the results by budgets terms.
func ByBudgets(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBudgetsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRecurringExpensesCount orders the results by recurring_expenses count.
func ByRecurringExpensesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRecurringExpensesStep(), opts...)
	}
}

// ByRecurringExpenses orders the results by recurring_expenses terms.
func ByRecurringExpenses(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRecurringExpensesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByChatMessagesCount orders the results by chat_messages count.
func ByChatMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChatMessagesStep(), opts...)
	}
}

// ByChatMessages orders the results by chat_messages terms.
func ByChatMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChatMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SessionsTable, SessionsColumn),
	)
}
func newCategoriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CategoriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, CategoriesTable, CategoriesColumn),
	)
}
func newExpensesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ExpensesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ExpensesTable, ExpensesColumn),
	)
}
func newBudgetsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BudgetsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BudgetsTable, BudgetsColumn),
	)
}
func newRecurringExpensesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RecurringExpensesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RecurringExpensesTable, RecurringExpensesColumn),
	)
}
func newChatMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChatMessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ChatMessagesTable, ChatMessagesColumn),
	)
}
