// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"expense-server/ent/budget"
	"expense-server/ent/category"
	"expense-server/ent/user"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BudgetCreate is the builder for creating a Budget entity.
type BudgetCreate struct {
	config
	mutation *BudgetMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (bc *BudgetCreate) SetUserID(i int) *BudgetCreate {
	bc.mutation.SetUserID(i)
	return bc
}

// SetCategoryID sets the "category_id" field.
func (bc *BudgetCreate) SetCategoryID(i int) *BudgetCreate {
	bc.mutation.SetCategoryID(i)
	return bc
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (bc *BudgetCreate) SetNillableCategoryID(i *int) *BudgetCreate {
	if i != nil {
		bc.SetCategoryID(*i)
	}
	return bc
}

// SetAmount sets the "amount" field.
func (bc *BudgetCreate) SetAmount(f float64) *BudgetCreate {
	bc.mutation.SetAmount(f)
	return bc
}

// SetPeriod sets the "period" field.
func (bc *BudgetCreate) SetPeriod(s string) *BudgetCreate {
	bc.mutation.SetPeriod(s)
	return bc
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (bc *BudgetCreate) SetNillablePeriod(s *string) *BudgetCreate {
	if s != nil {
		bc.SetPeriod(*s)
	}
	return bc
}

// SetStartDate sets the "start_date" field.
func (bc *BudgetCreate) SetStartDate(t time.Time) *BudgetCreate {
	bc.mutation.SetStartDate(t)
	return bc
}

// SetEndDate sets the "end_date" field.
func (bc *BudgetCreate) SetEndDate(t time.Time) *BudgetCreate {
	bc.mutation.SetEndDate(t)
	return bc
}

// SetCreatedAt sets the "created_at" field.
func (bc *BudgetCreate) SetCreatedAt(t time.Time) *BudgetCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BudgetCreate) SetNillableCreatedAt(t *time.Time) *BudgetCreate {
	if t != nil {
		bc.SetCreatedAt(*t)
	}
	return bc
}

// SetID sets the "id" field.
func (bc *BudgetCreate) SetID(i int) *BudgetCreate {
	bc.mutation.SetID(i)
	return bc
}

// SetUser sets the "user" edge to the User entity.
func (bc *BudgetCreate) SetUser(u *User) *BudgetCreate {
	return bc.SetUserID(u.ID)
}

// SetCategory sets the "category" edge to the Category entity.
func (bc *BudgetCreate) SetCategory(c *Category) *BudgetCreate {
	return bc.SetCategoryID(c.ID)
}

// Mutation returns the BudgetMutation object of the builder.
func (bc *BudgetCreate) Mutation() *BudgetMutation {
	return bc.mutation
}

// Save creates the Budget in the database.
func (bc *BudgetCreate) Save(ctx context.Context) (*Budget, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BudgetCreate) SaveX(ctx context.Context) *Budget {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BudgetCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BudgetCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BudgetCreate) defaults() {
	if _, ok := bc.mutation.Period(); !ok {
		v := budget.DefaultPeriod
		bc.mutation.SetPeriod(v)
	}
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := budget.DefaultCreatedAt()
		bc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BudgetCreate) check() error {
	if _, ok := bc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Budget.user_id"`)}
	}
	if _, ok := bc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Budget.amount"`)}
	}
	if _, ok := bc.mutation.Period(); !ok {
		return &ValidationError{Name: "period", err: errors.New(`ent: missing required field "Budget.period"`)}
	}
	if _, ok := bc.mutation.StartDate(); !ok {
		return &ValidationError{Name: "start_date", err: errors.New(`ent: missing required field "Budget.start_date"`)}
	}
	if _, ok := bc.mutation.EndDate(); !ok {
		return &ValidationError{Name: "end_date", err: errors.New(`ent: missing required field "Budget.end_date"`)}
	}
	if len(bc.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Budget.user"`)}
	}
	return nil
}

func (bc *BudgetCreate) sqlSave(ctx context.Context) (*Budget, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BudgetCreate) createSpec() (*Budget, *sqlgraph.CreateSpec) {
	var (
		_node = &Budget{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(budget.Table, sqlgraph.NewFieldSpec(budget.FieldID, field.TypeInt))
	)
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bc.mutation.Amount(); ok {
		_spec.SetField(budget.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := bc.mutation.Period(); ok {
		_spec.SetField(budget.FieldPeriod, field.TypeString, value)
		_node.Period = value
	}
	if value, ok := bc.mutation.StartDate(); ok {
		_spec.SetField(budget.FieldStartDate, field.TypeTime, value)
		_node.StartDate = value
	}
	if value, ok := bc.mutation.EndDate(); ok {
		_spec.SetField(budget.FieldEndDate, field.TypeTime, value)
		_node.EndDate = value
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(budget.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := bc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.UserTable,
			Columns: []string{budget.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := bc.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CategoryTable,
			Columns: []string{budget.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BudgetCreateBulk is the builder for creating many Budget entities in bulk.
type BudgetCreateBulk struct {
	config
	err      error
	builders []*BudgetCreate
}

// Save creates the Budget entities in the database.
func (bcb *BudgetCreateBulk) Save(ctx context.Context) ([]*Budget, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Budget, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BudgetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BudgetCreateBulk) SaveX(ctx context.Context) []*Budget {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BudgetCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BudgetCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
