// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"expense-server/ent/budget"
	"expense-server/ent/category"
	"expense-server/ent/predicate"
	"expense-server/ent/user"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BudgetUpdate is the builder for updating Budget entities.
type BudgetUpdate struct {
	config
	hooks    []Hook
	mutation *BudgetMutation
}

// Where appends a list predicates to the BudgetUpdate builder.
func (bu *BudgetUpdate) Where(ps ...predicate.Budget) *BudgetUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetUserID sets the "user_id" field.
func (bu *BudgetUpdate) SetUserID(i int) *BudgetUpdate {
	bu.mutation.SetUserID(i)
	return bu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (bu *BudgetUpdate) SetNillableUserID(i *int) *BudgetUpdate {
	if i != nil {
		bu.SetUserID(*i)
	}
	return bu
}

// SetCategoryID sets the "category_id" field.
func (bu *BudgetUpdate) SetCategoryID(i int) *BudgetUpdate {
	bu.mutation.SetCategoryID(i)
	return bu
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (bu *BudgetUpdate) SetNillableCategoryID(i *int) *BudgetUpdate {
	if i != nil {
		bu.SetCategoryID(*i)
	}
	return bu
}

// ClearCategoryID clears the value of the "category_id" field.
func (bu *BudgetUpdate) ClearCategoryID() *BudgetUpdate {
	bu.mutation.ClearCategoryID()
	return bu
}

// SetAmount sets the "amount" field.
func (bu *BudgetUpdate) SetAmount(f float64) *BudgetUpdate {
	bu.mutation.ResetAmount()
	bu.mutation.SetAmount(f)
	return bu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (bu *BudgetUpdate) SetNillableAmount(f *float64) *BudgetUpdate {
	if f != nil {
		bu.SetAmount(*f)
	}
	return bu
}

// AddAmount adds f to the "amount" field.
func (bu *BudgetUpdate) AddAmount(f float64) *BudgetUpdate {
	bu.mutation.AddAmount(f)
	return bu
}

// SetPeriod sets the "period" field.
func (bu *BudgetUpdate) SetPeriod(s string) *BudgetUpdate {
	bu.mutation.SetPeriod(s)
	return bu
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (bu *BudgetUpdate) SetNillablePeriod(s *string) *BudgetUpdate {
	if s != nil {
		bu.SetPeriod(*s)
	}
	return bu
}

// SetStartDate sets the "start_date" field.
func (bu *BudgetUpdate) SetStartDate(t time.Time) *BudgetUpdate {
	bu.mutation.SetStartDate(t)
	return bu
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (bu *BudgetUpdate) SetNillableStartDate(t *time.Time) *BudgetUpdate {
	if t != nil {
		bu.SetStartDate(*t)
	}
	return bu
}

// SetEndDate sets the "end_date" field.
func (bu *BudgetUpdate) SetEndDate(t time.Time) *BudgetUpdate {
	bu.mutation.SetEndDate(t)
	return bu
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (bu *BudgetUpdate) SetNillableEndDate(t *time.Time) *BudgetUpdate {
	if t != nil {
		bu.SetEndDate(*t)
	}
	return bu
}

// SetCreatedAt sets the "created_at" field.
func (bu *BudgetUpdate) SetCreatedAt(t time.Time) *BudgetUpdate {
	bu.mutation.SetCreatedAt(t)
	return bu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bu *BudgetUpdate) SetNillableCreatedAt(t *time.Time) *BudgetUpdate {
	if t != nil {
		bu.SetCreatedAt(*t)
	}
	return bu
}

// SetUser sets the "user" edge to the User entity.
func (bu *BudgetUpdate) SetUser(u *User) *BudgetUpdate {
	return bu.SetUserID(u.ID)
}

// SetCategory sets the "category" edge to the Category entity.
func (bu *BudgetUpdate) SetCategory(c *Category) *BudgetUpdate {
	return bu.SetCategoryID(c.ID)
}

// Mutation returns the BudgetMutation object of the builder.
func (bu *BudgetUpdate) Mutation() *BudgetMutation {
	return bu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (bu *BudgetUpdate) ClearUser() *BudgetUpdate {
	bu.mutation.ClearUser()
	return bu
}

// ClearCategory clears the "category" edge to the Category entity.
func (bu *BudgetUpdate) ClearCategory() *BudgetUpdate {
	bu.mutation.ClearCategory()
	return bu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BudgetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BudgetUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BudgetUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BudgetUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bu *BudgetUpdate) check() error {
	if bu.mutation.UserCleared() && len(bu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Budget.user"`)
	}
	return nil
}

func (bu *BudgetUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(budget.Table, budget.Columns, sqlgraph.NewFieldSpec(budget.FieldID, field.TypeInt))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Amount(); ok {
		_spec.SetField(budget.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := bu.mutation.AddedAmount(); ok {
		_spec.AddField(budget.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := bu.mutation.Period(); ok {
		_spec.SetField(budget.FieldPeriod, field.TypeString, value)
	}
	if value, ok := bu.mutation.StartDate(); ok {
		_spec.SetField(budget.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := bu.mutation.EndDate(); ok {
		_spec.SetField(budget.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := bu.mutation.CreatedAt(); ok {
		_spec.SetField(budget.FieldCreatedAt, field.TypeTime, value)
	}
	if bu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.UserTable,
			Columns: []string{budget.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.UserTable,
			Columns: []string{budget.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if bu.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CategoryTable,
			Columns: []string{budget.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CategoryTable,
			Columns: []string{budget.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BudgetUpdateOne is the builder for updating a single Budget entity.
type BudgetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BudgetMutation
}

// SetUserID sets the "user_id" field.
func (buo *BudgetUpdateOne) SetUserID(i int) *BudgetUpdateOne {
	buo.mutation.SetUserID(i)
	return buo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (buo *BudgetUpdateOne) SetNillableUserID(i *int) *BudgetUpdateOne {
	if i != nil {
		buo.SetUserID(*i)
	}
	return buo
}

// SetCategoryID sets the "category_id" field.
func (buo *BudgetUpdateOne) SetCategoryID(i int) *BudgetUpdateOne {
	buo.mutation.SetCategoryID(i)
	return buo
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (buo *BudgetUpdateOne) SetNillableCategoryID(i *int) *BudgetUpdateOne {
	if i != nil {
		buo.SetCategoryID(*i)
	}
	return buo
}

// ClearCategoryID clears the value of the "category_id" field.
func (buo *BudgetUpdateOne) ClearCategoryID() *BudgetUpdateOne {
	buo.mutation.ClearCategoryID()
	return buo
}

// SetAmount sets the "amount" field.
func (buo *BudgetUpdateOne) SetAmount(f float64) *BudgetUpdateOne {
	buo.mutation.ResetAmount()
	buo.mutation.SetAmount(f)
	return buo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (buo *BudgetUpdateOne) SetNillableAmount(f *float64) *BudgetUpdateOne {
	if f != nil {
		buo.SetAmount(*f)
	}
	return buo
}

// AddAmount adds f to the "amount" field.
func (buo *BudgetUpdateOne) AddAmount(f float64) *BudgetUpdateOne {
	buo.mutation.AddAmount(f)
	return buo
}

// SetPeriod sets the "period" field.
func (buo *BudgetUpdateOne) SetPeriod(s string) *BudgetUpdateOne {
	buo.mutation.SetPeriod(s)
	return buo
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (buo *BudgetUpdateOne) SetNillablePeriod(s *string) *BudgetUpdateOne {
	if s != nil {
		buo.SetPeriod(*s)
	}
	return buo
}

// SetStartDate sets the "start_date" field.
func (buo *BudgetUpdateOne) SetStartDate(t time.Time) *BudgetUpdateOne {
	buo.mutation.SetStartDate(t)
	return buo
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (buo *BudgetUpdateOne) SetNillableStartDate(t *time.Time) *BudgetUpdateOne {
	if t != nil {
		buo.SetStartDate(*t)
	}
	return buo
}

// SetEndDate sets the "end_date" field.
func (buo *BudgetUpdateOne) SetEndDate(t time.Time) *BudgetUpdateOne {
	buo.mutation.SetEndDate(t)
	return buo
}

// SetNillableEndDate sets the "end_date" field if the given value is not nil.
func (buo *BudgetUpdateOne) SetNillableEndDate(t *time.Time) *BudgetUpdateOne {
	if t != nil {
		buo.SetEndDate(*t)
	}
	return buo
}

// SetCreatedAt sets the "created_at" field.
func (buo *BudgetUpdateOne) SetCreatedAt(t time.Time) *BudgetUpdateOne {
	buo.mutation.SetCreatedAt(t)
	return buo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (buo *BudgetUpdateOne) SetNillableCreatedAt(t *time.Time) *BudgetUpdateOne {
	if t != nil {
		buo.SetCreatedAt(*t)
	}
	return buo
}

// SetUser sets the "user" edge to the User entity.
func (buo *BudgetUpdateOne) SetUser(u *User) *BudgetUpdateOne {
	return buo.SetUserID(u.ID)
}

// SetCategory sets the "category" edge to the Category entity.
func (buo *BudgetUpdateOne) SetCategory(c *Category) *BudgetUpdateOne {
	return buo.SetCategoryID(c.ID)
}

// Mutation returns the BudgetMutation object of the builder.
func (buo *BudgetUpdateOne) Mutation() *BudgetMutation {
	return buo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (buo *BudgetUpdateOne) ClearUser() *BudgetUpdateOne {
	buo.mutation.ClearUser()
	return buo
}

// ClearCategory clears the "category" edge to the Category entity.
func (buo *BudgetUpdateOne) ClearCategory() *BudgetUpdateOne {
	buo.mutation.ClearCategory()
	return buo
}

// Where appends a list predicates to the BudgetUpdate builder.
func (buo *BudgetUpdateOne) Where(ps ...predicate.Budget) *BudgetUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BudgetUpdateOne) Select(field string, fields ...string) *BudgetUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Budget entity.
func (buo *BudgetUpdateOne) Save(ctx context.Context) (*Budget, error) {
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BudgetUpdateOne) SaveX(ctx context.Context) *Budget {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BudgetUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BudgetUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (buo *BudgetUpdateOne) check() error {
	if buo.mutation.UserCleared() && len(buo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Budget.user"`)
	}
	return nil
}

func (buo *BudgetUpdateOne) sqlSave(ctx context.Context) (_node *Budget, err error) {
	if err := buo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(budget.Table, budget.Columns, sqlgraph.NewFieldSpec(budget.FieldID, field.TypeInt))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Budget.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, budget.FieldID)
		for _, f := range fields {
			if !budget.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != budget.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Amount(); ok {
		_spec.SetField(budget.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := buo.mutation.AddedAmount(); ok {
		_spec.AddField(budget.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := buo.mutation.Period(); ok {
		_spec.SetField(budget.FieldPeriod, field.TypeString, value)
	}
	if value, ok := buo.mutation.StartDate(); ok {
		_spec.SetField(budget.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := buo.mutation.EndDate(); ok {
		_spec.SetField(budget.FieldEndDate, field.TypeTime, value)
	}
	if value, ok := buo.mutation.CreatedAt(); ok {
		_spec.SetField(budget.FieldCreatedAt, field.TypeTime, value)
	}
	if buo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.UserTable,
			Columns: []string{budget.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.UserTable,
			Columns: []string{budget.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if buo.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CategoryTable,
			Columns: []string{budget.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   budget.CategoryTable,
			Columns: []string{budget.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Budget{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{budget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
