// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"expense-server/ent/budget"
	"expense-server/ent/category"
	"expense-server/ent/expense"
	"expense-server/ent/predicate"
	"expense-server/ent/recurringexpense"
	"expense-server/ent/user"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CategoryUpdate is the builder for updating Category entities.
type CategoryUpdate struct {
	config
	hooks    []Hook
	mutation *CategoryMutation
}

// Where appends a list predicates to the CategoryUpdate builder.
func (cu *CategoryUpdate) Where(ps ...predicate.Category) *CategoryUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUserID sets the "user_id" field.
func (cu *CategoryUpdate) SetUserID(i int) *CategoryUpdate {
	cu.mutation.SetUserID(i)
	return cu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (cu *CategoryUpdate) SetNillableUserID(i *int) *CategoryUpdate {
	if i != nil {
		cu.SetUserID(*i)
	}
	return cu
}

// ClearUserID clears the value of the "user_id" field.
func (cu *CategoryUpdate) ClearUserID() *CategoryUpdate {
	cu.mutation.ClearUserID()
	return cu
}

// SetName sets the "name" field.
func (cu *CategoryUpdate) SetName(s string) *CategoryUpdate {
	cu.mutation.SetName(s)
	return cu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cu *CategoryUpdate) SetNillableName(s *string) *CategoryUpdate {
	if s != nil {
		cu.SetName(*s)
	}
	return cu
}

// SetColor sets the "color" field.
func (cu *CategoryUpdate) SetColor(s string) *CategoryUpdate {
	cu.mutation.SetColor(s)
	return cu
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (cu *CategoryUpdate) SetNillableColor(s *string) *CategoryUpdate {
	if s != nil {
		cu.SetColor(*s)
	}
	return cu
}

// SetCreatedAt sets the "created_at" field.
func (cu *CategoryUpdate) SetCreatedAt(t time.Time) *CategoryUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cu *CategoryUpdate) SetNillableCreatedAt(t *time.Time) *CategoryUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// SetUser sets the "user" edge to the User entity.
func (cu *CategoryUpdate) SetUser(u *User) *CategoryUpdate {
	return cu.SetUserID(u.ID)
}

// AddExpenseIDs adds the "expenses" edge to the Expense entity by IDs.
func (cu *CategoryUpdate) AddExpenseIDs(ids ...int) *CategoryUpdate {
	cu.mutation.AddExpenseIDs(ids...)
	return cu
}

// AddExpenses adds the "expenses" edges to the Expense entity.
func (cu *CategoryUpdate) AddExpenses(e ...*Expense) *CategoryUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return cu.AddExpenseIDs(ids...)
}

// AddBudgetIDs adds the "budgets" edge to the Budget entity by IDs.
func (cu *CategoryUpdate) AddBudgetIDs(ids ...int) *CategoryUpdate {
	cu.mutation.AddBudgetIDs(ids...)
	return cu
}

// AddBudgets adds the "budgets" edges to the Budget entity.
func (cu *CategoryUpdate) AddBudgets(b ...*Budget) *CategoryUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return cu.AddBudgetIDs(ids...)
}

// AddRecurringExpenseIDs adds the "recurring_expenses" edge to the RecurringExpense entity by IDs.
func (cu *CategoryUpdate) AddRecurringExpenseIDs(ids ...int) *CategoryUpdate {
	cu.mutation.AddRecurringExpenseIDs(ids...)
	return cu
}

// AddRecurringExpenses adds the "recurring_expenses" edges to the RecurringExpense entity.
func (cu *CategoryUpdate) AddRecurringExpenses(r ...*RecurringExpense) *CategoryUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.AddRecurringExpenseIDs(ids...)
}

// Mutation returns the CategoryMutation object of the builder.
func (cu *CategoryUpdate) Mutation() *CategoryMutation {
	return cu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (cu *CategoryUpdate) ClearUser() *CategoryUpdate {
	cu.mutation.ClearUser()
	return cu
}

// ClearExpenses clears all "expenses" edges to the Expense entity.
func (cu *CategoryUpdate) ClearExpenses() *CategoryUpdate {
	cu.mutation.ClearExpenses()
	return cu
}

// RemoveExpenseIDs removes the "expenses" edge to Expense entities by IDs.
func (cu *CategoryUpdate) RemoveExpenseIDs(ids ...int) *CategoryUpdate {
	cu.mutation.RemoveExpenseIDs(ids...)
	return cu
}

// RemoveExpenses removes "expenses" edges to Expense entities.
func (cu *CategoryUpdate) RemoveExpenses(e ...*Expense) *CategoryUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return cu.RemoveExpenseIDs(ids...)
}

// ClearBudgets clears all "budgets" edges to the Budget entity.
func (cu *CategoryUpdate) ClearBudgets() *CategoryUpdate {
	cu.mutation.ClearBudgets()
	return cu
}

// RemoveBudgetIDs removes the "budgets" edge to Budget entities by IDs.
func (cu *CategoryUpdate) RemoveBudgetIDs(ids ...int) *CategoryUpdate {
	cu.mutation.RemoveBudgetIDs(ids...)
	return cu
}

// RemoveBudgets removes "budgets" edges to Budget entities.
func (cu *CategoryUpdate) RemoveBudgets(b ...*Budget) *CategoryUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return cu.RemoveBudgetIDs(ids...)
}

// ClearRecurringExpenses clears all "recurring_expenses" edges to the RecurringExpense entity.
func (cu *CategoryUpdate) ClearRecurringExpenses() *CategoryUpdate {
	cu.mutation.ClearRecurringExpenses()
	return cu
}

// RemoveRecurringExpenseIDs removes the "recurring_expenses" edge to RecurringExpense entities by IDs.
func (cu *CategoryUpdate) RemoveRecurringExpenseIDs(ids ...int) *CategoryUpdate {
	cu.mutation.RemoveRecurringExpenseIDs(ids...)
	return cu
}

// RemoveRecurringExpenses removes "recurring_expenses" edges to RecurringExpense entities.
func (cu *CategoryUpdate) RemoveRecurringExpenses(r ...*RecurringExpense) *CategoryUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cu.RemoveRecurringExpenseIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CategoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CategoryUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CategoryUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CategoryUpdate) check() error {
	if v, ok := cu.mutation.Name(); ok {
		if err := category.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Category.name": %w`, err)}
		}
	}
	return nil
}

func (cu *CategoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(category.Table, category.Columns, sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Name(); ok {
		_spec.SetField(category.FieldName, field.TypeString, value)
	}
	if value, ok := cu.mutation.Color(); ok {
		_spec.SetField(category.FieldColor, field.TypeString, value)
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.SetField(category.FieldCreatedAt, field.TypeTime, value)
	}
	if cu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   category.UserTable,
			Columns: []string{category.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   category.UserTable,
			Columns: []string{category.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.ExpensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.ExpensesTable,
			Columns: []string{category.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedExpensesIDs(); len(nodes) > 0 && !cu.mutation.ExpensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.ExpensesTable,
			Columns: []string{category.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.ExpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.ExpensesTable,
			Columns: []string{category.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.BudgetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.BudgetsTable,
			Columns: []string{category.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedBudgetsIDs(); len(nodes) > 0 && !cu.mutation.BudgetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.BudgetsTable,
			Columns: []string{category.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.BudgetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.BudgetsTable,
			Columns: []string{category.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.RecurringExpensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.RecurringExpensesTable,
			Columns: []string{category.RecurringExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedRecurringExpensesIDs(); len(nodes) > 0 && !cu.mutation.RecurringExpensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.RecurringExpensesTable,
			Columns: []string{category.RecurringExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RecurringExpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.RecurringExpensesTable,
			Columns: []string{category.RecurringExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{category.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// CategoryUpdateOne is the builder for updating a single Category entity.
type CategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CategoryMutation
}

// SetUserID sets the "user_id" field.
func (cuo *CategoryUpdateOne) SetUserID(i int) *CategoryUpdateOne {
	cuo.mutation.SetUserID(i)
	return cuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (cuo *CategoryUpdateOne) SetNillableUserID(i *int) *CategoryUpdateOne {
	if i != nil {
		cuo.SetUserID(*i)
	}
	return cuo
}

// ClearUserID clears the value of the "user_id" field.
func (cuo *CategoryUpdateOne) ClearUserID() *CategoryUpdateOne {
	cuo.mutation.ClearUserID()
	return cuo
}

// SetName sets the "name" field.
func (cuo *CategoryUpdateOne) SetName(s string) *CategoryUpdateOne {
	cuo.mutation.SetName(s)
	return cuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (cuo *CategoryUpdateOne) SetNillableName(s *string) *CategoryUpdateOne {
	if s != nil {
		cuo.SetName(*s)
	}
	return cuo
}

// SetColor sets the "color" field.
func (cuo *CategoryUpdateOne) SetColor(s string) *CategoryUpdateOne {
	cuo.mutation.SetColor(s)
	return cuo
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (cuo *CategoryUpdateOne) SetNillableColor(s *string) *CategoryUpdateOne {
	if s != nil {
		cuo.SetColor(*s)
	}
	return cuo
}

// SetCreatedAt sets the "created_at" field.
func (cuo *CategoryUpdateOne) SetCreatedAt(t time.Time) *CategoryUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuo *CategoryUpdateOne) SetNillableCreatedAt(t *time.Time) *CategoryUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// SetUser sets the "user" edge to the User entity.
func (cuo *CategoryUpdateOne) SetUser(u *User) *CategoryUpdateOne {
	return cuo.SetUserID(u.ID)
}

// AddExpenseIDs adds the "expenses" edge to the Expense entity by IDs.
func (cuo *CategoryUpdateOne) AddExpenseIDs(ids ...int) *CategoryUpdateOne {
	cuo.mutation.AddExpenseIDs(ids...)
	return cuo
}

// AddExpenses adds the "expenses" edges to the Expense entity.
func (cuo *CategoryUpdateOne) AddExpenses(e ...*Expense) *CategoryUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return cuo.AddExpenseIDs(ids...)
}

// AddBudgetIDs adds the "budgets" edge to the Budget entity by IDs.
func (cuo *CategoryUpdateOne) AddBudgetIDs(ids ...int) *CategoryUpdateOne {
	cuo.mutation.AddBudgetIDs(ids...)
	return cuo
}

// AddBudgets adds the "budgets" edges to the Budget entity.
func (cuo *CategoryUpdateOne) AddBudgets(b ...*Budget) *CategoryUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return cuo.AddBudgetIDs(ids...)
}

// AddRecurringExpenseIDs adds the "recurring_expenses" edge to the RecurringExpense entity by IDs.
func (cuo *CategoryUpdateOne) AddRecurringExpenseIDs(ids ...int) *CategoryUpdateOne {
	cuo.mutation.AddRecurringExpenseIDs(ids...)
	return cuo
}

// AddRecurringExpenses adds the "recurring_expenses" edges to the RecurringExpense entity.
func (cuo *CategoryUpdateOne) AddRecurringExpenses(r ...*RecurringExpense) *CategoryUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.AddRecurringExpenseIDs(ids...)
}

// Mutation returns the CategoryMutation object of the builder.
func (cuo *CategoryUpdateOne) Mutation() *CategoryMutation {
	return cuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (cuo *CategoryUpdateOne) ClearUser() *CategoryUpdateOne {
	cuo.mutation.ClearUser()
	return cuo
}

// ClearExpenses clears all "expenses" edges to the Expense entity.
func (cuo *CategoryUpdateOne) ClearExpenses() *CategoryUpdateOne {
	cuo.mutation.ClearExpenses()
	return cuo
}

// RemoveExpenseIDs removes the "expenses" edge to Expense entities by IDs.
func (cuo *CategoryUpdateOne) RemoveExpenseIDs(ids ...int) *CategoryUpdateOne {
	cuo.mutation.RemoveExpenseIDs(ids...)
	return cuo
}

// RemoveExpenses removes "expenses" edges to Expense entities.
func (cuo *CategoryUpdateOne) RemoveExpenses(e ...*Expense) *CategoryUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return cuo.RemoveExpenseIDs(ids...)
}

// ClearBudgets clears all "budgets" edges to the Budget entity.
func (cuo *CategoryUpdateOne) ClearBudgets() *CategoryUpdateOne {
	cuo.mutation.ClearBudgets()
	return cuo
}

// RemoveBudgetIDs removes the "budgets" edge to Budget entities by IDs.
func (cuo *CategoryUpdateOne) RemoveBudgetIDs(ids ...int) *CategoryUpdateOne {
	cuo.mutation.RemoveBudgetIDs(ids...)
	return cuo
}

// RemoveBudgets removes "budgets" edges to Budget entities.
func (cuo *CategoryUpdateOne) RemoveBudgets(b ...*Budget) *CategoryUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return cuo.RemoveBudgetIDs(ids...)
}

// ClearRecurringExpenses clears all "recurring_expenses" edges to the RecurringExpense entity.
func (cuo *CategoryUpdateOne) ClearRecurringExpenses() *CategoryUpdateOne {
	cuo.mutation.ClearRecurringExpenses()
	return cuo
}

// RemoveRecurringExpenseIDs removes the "recurring_expenses" edge to RecurringExpense entities by IDs.
func (cuo *CategoryUpdateOne) RemoveRecurringExpenseIDs(ids ...int) *CategoryUpdateOne {
	cuo.mutation.RemoveRecurringExpenseIDs(ids...)
	return cuo
}

// RemoveRecurringExpenses removes "recurring_expenses" edges to RecurringExpense entities.
func (cuo *CategoryUpdateOne) RemoveRecurringExpenses(r ...*RecurringExpense) *CategoryUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return cuo.RemoveRecurringExpenseIDs(ids...)
}

// Where appends a list predicates to the CategoryUpdate builder.
func (cuo *CategoryUpdateOne) Where(ps ...predicate.Category) *CategoryUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CategoryUpdateOne) Select(field string, fields ...string) *CategoryUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Category entity.
func (cuo *CategoryUpdateOne) Save(ctx context.Context) (*Category, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CategoryUpdateOne) SaveX(ctx context.Context) *Category {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CategoryUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CategoryUpdateOne) check() error {
	if v, ok := cuo.mutation.Name(); ok {
		if err := category.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Category.name": %w`, err)}
		}
	}
	return nil
}

func (cuo *CategoryUpdateOne) sqlSave(ctx context.Context) (_node *Category, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(category.Table, category.Columns, sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Category.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, category.FieldID)
		for _, f := range fields {
			if !category.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != category.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Name(); ok {
		_spec.SetField(category.FieldName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Color(); ok {
		_spec.SetField(category.FieldColor, field.TypeString, value)
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.SetField(category.FieldCreatedAt, field.TypeTime, value)
	}
	if cuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   category.UserTable,
			Columns: []string{category.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   category.UserTable,
			Columns: []string{category.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.ExpensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.ExpensesTable,
			Columns: []string{category.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedExpensesIDs(); len(nodes) > 0 && !cuo.mutation.ExpensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.ExpensesTable,
			Columns: []string{category.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.ExpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.ExpensesTable,
			Columns: []string{category.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.BudgetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.BudgetsTable,
			Columns: []string{category.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedBudgetsIDs(); len(nodes) > 0 && !cuo.mutation.BudgetsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.BudgetsTable,
			Columns: []string{category.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.BudgetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.BudgetsTable,
			Columns: []string{category.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.RecurringExpensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.RecurringExpensesTable,
			Columns: []string{category.RecurringExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedRecurringExpensesIDs(); len(nodes) > 0 && !cuo.mutation.RecurringExpensesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.RecurringExpensesTable,
			Columns: []string{category.RecurringExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RecurringExpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   category.RecurringExpensesTable,
			Columns: []string{category.RecurringExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Category{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{category.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
