// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"expense-server/ent/category"
	"expense-server/ent/expense"
	"expense-server/ent/predicate"
	"expense-server/ent/user"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExpenseUpdate is the builder for updating Expense entities.
type ExpenseUpdate struct {
	config
	hooks    []Hook
	mutation *ExpenseMutation
}

// Where appends a list predicates to the ExpenseUpdate builder.
func (eu *ExpenseUpdate) Where(ps ...predicate.Expense) *ExpenseUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetUserID sets the "user_id" field.
func (eu *ExpenseUpdate) SetUserID(i int) *ExpenseUpdate {
	eu.mutation.SetUserID(i)
	return eu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (eu *ExpenseUpdate) SetNillableUserID(i *int) *ExpenseUpdate {
	if i != nil {
		eu.SetUserID(*i)
	}
	return eu
}

// SetTitle sets the "title" field.
func (eu *ExpenseUpdate) SetTitle(s string) *ExpenseUpdate {
	eu.mutation.SetTitle(s)
	return eu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (eu *ExpenseUpdate) SetNillableTitle(s *string) *ExpenseUpdate {
	if s != nil {
		eu.SetTitle(*s)
	}
	return eu
}

// SetAmount sets the "amount" field.
func (eu *ExpenseUpdate) SetAmount(f float64) *ExpenseUpdate {
	eu.mutation.ResetAmount()
	eu.mutation.SetAmount(f)
	return eu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (eu *ExpenseUpdate) SetNillableAmount(f *float64) *ExpenseUpdate {
	if f != nil {
		eu.SetAmount(*f)
	}
	return eu
}

// AddAmount adds f to the "amount" field.
func (eu *ExpenseUpdate) AddAmount(f float64) *ExpenseUpdate {
	eu.mutation.AddAmount(f)
	return eu
}

// SetCategory sets the "category" field.
func (eu *ExpenseUpdate) SetCategory(s string) *ExpenseUpdate {
	eu.mutation.SetCategory(s)
	return eu
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (eu *ExpenseUpdate) SetNillableCategory(s *string) *ExpenseUpdate {
	if s != nil {
		eu.SetCategory(*s)
	}
	return eu
}

// ClearCategory clears the value of the "category" field.
func (eu *ExpenseUpdate) ClearCategory() *ExpenseUpdate {
	eu.mutation.ClearCategory()
	return eu
}

// SetCategoryID sets the "category_id" field.
func (eu *ExpenseUpdate) SetCategoryID(i int) *ExpenseUpdate {
	eu.mutation.SetCategoryID(i)
	return eu
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (eu *ExpenseUpdate) SetNillableCategoryID(i *int) *ExpenseUpdate {
	if i != nil {
		eu.SetCategoryID(*i)
	}
	return eu
}

// ClearCategoryID clears the value of the "category_id" field.
func (eu *ExpenseUpdate) ClearCategoryID() *ExpenseUpdate {
	eu.mutation.ClearCategoryID()
	return eu
}

// SetCreatedAt sets the "created_at" field.
func (eu *ExpenseUpdate) SetCreatedAt(t time.Time) *ExpenseUpdate {
	eu.mutation.SetCreatedAt(t)
	return eu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (eu *ExpenseUpdate) SetNillableCreatedAt(t *time.Time) *ExpenseUpdate {
	if t != nil {
		eu.SetCreatedAt(*t)
	}
	return eu
}

// SetUser sets the "user" edge to the User entity.
func (eu *ExpenseUpdate) SetUser(u *User) *ExpenseUpdate {
	return eu.SetUserID(u.ID)
}

// SetCategoryRefID sets the "category_ref" edge to the Category entity by ID.
func (eu *ExpenseUpdate) SetCategoryRefID(id int) *ExpenseUpdate {
	eu.mutation.SetCategoryRefID(id)
	return eu
}

// SetNillableCategoryRefID sets the "category_ref" edge to the Category entity by ID if the given value is not nil.
func (eu *ExpenseUpdate) SetNillableCategoryRefID(id *int) *ExpenseUpdate {
	if id != nil {
		eu = eu.SetCategoryRefID(*id)
	}
	return eu
}

// SetCategoryRef sets the "category_ref" edge to the Category entity.
func (eu *ExpenseUpdate) SetCategoryRef(c *Category) *ExpenseUpdate {
	return eu.SetCategoryRefID(c.ID)
}

// Mutation returns the ExpenseMutation object of the builder.
func (eu *ExpenseUpdate) Mutation() *ExpenseMutation {
	return eu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (eu *ExpenseUpdate) ClearUser() *ExpenseUpdate {
	eu.mutation.ClearUser()
	return eu
}

// ClearCategoryRef clears the "category_ref" edge to the Category entity.
func (eu *ExpenseUpdate) ClearCategoryRef() *ExpenseUpdate {
	eu.mutation.ClearCategoryRef()
	return eu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *ExpenseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *ExpenseUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *ExpenseUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *ExpenseUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *ExpenseUpdate) check() error {
	if v, ok := eu.mutation.Title(); ok {
		if err := expense.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Expense.title": %w`, err)}
		}
	}
	if eu.mutation.UserCleared() && len(eu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Expense.user"`)
	}
	return nil
}

func (eu *ExpenseUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(expense.Table, expense.Columns, sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.Title(); ok {
		_spec.SetField(expense.FieldTitle, field.TypeString, value)
	}
	if value, ok := eu.mutation.Amount(); ok {
		_spec.SetField(expense.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := eu.mutation.AddedAmount(); ok {
		_spec.AddField(expense.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := eu.mutation.Category(); ok {
		_spec.SetField(expense.FieldCategory, field.TypeString, value)
	}
	if eu.mutation.CategoryCleared() {
		_spec.ClearField(expense.FieldCategory, field.TypeString)
	}
	if value, ok := eu.mutation.CreatedAt(); ok {
		_spec.SetField(expense.FieldCreatedAt, field.TypeTime, value)
	}
	if eu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expense.UserTable,
			Columns: []string{expense.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expense.UserTable,
			Columns: []string{expense.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if eu.mutation.CategoryRefCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expense.CategoryRefTable,
			Columns: []string{expense.CategoryRefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.CategoryRefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expense.CategoryRefTable,
			Columns: []string{expense.CategoryRefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{expense.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// ExpenseUpdateOne is the builder for updating a single Expense entity.
type ExpenseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ExpenseMutation
}

// SetUserID sets the "user_id" field.
func (euo *ExpenseUpdateOne) SetUserID(i int) *ExpenseUpdateOne {
	euo.mutation.SetUserID(i)
	return euo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (euo *ExpenseUpdateOne) SetNillableUserID(i *int) *ExpenseUpdateOne {
	if i != nil {
		euo.SetUserID(*i)
	}
	return euo
}

// SetTitle sets the "title" field.
func (euo *ExpenseUpdateOne) SetTitle(s string) *ExpenseUpdateOne {
	euo.mutation.SetTitle(s)
	return euo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (euo *ExpenseUpdateOne) SetNillableTitle(s *string) *ExpenseUpdateOne {
	if s != nil {
		euo.SetTitle(*s)
	}
	return euo
}

// SetAmount sets the "amount" field.
func (euo *ExpenseUpdateOne) SetAmount(f float64) *ExpenseUpdateOne {
	euo.mutation.ResetAmount()
	euo.mutation.SetAmount(f)
	return euo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (euo *ExpenseUpdateOne) SetNillableAmount(f *float64) *ExpenseUpdateOne {
	if f != nil {
		euo.SetAmount(*f)
	}
	return euo
}

// AddAmount adds f to the "amount" field.
func (euo *ExpenseUpdateOne) AddAmount(f float64) *ExpenseUpdateOne {
	euo.mutation.AddAmount(f)
	return euo
}

// SetCategory sets the "category" field.
func (euo *ExpenseUpdateOne) SetCategory(s string) *ExpenseUpdateOne {
	euo.mutation.SetCategory(s)
	return euo
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (euo *ExpenseUpdateOne) SetNillableCategory(s *string) *ExpenseUpdateOne {
	if s != nil {
		euo.SetCategory(*s)
	}
	return euo
}

// ClearCategory clears the value of the "category" field.
func (euo *ExpenseUpdateOne) ClearCategory() *ExpenseUpdateOne {
	euo.mutation.ClearCategory()
	return euo
}

// SetCategoryID sets the "category_id" field.
func (euo *ExpenseUpdateOne) SetCategoryID(i int) *ExpenseUpdateOne {
	euo.mutation.SetCategoryID(i)
	return euo
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (euo *ExpenseUpdateOne) SetNillableCategoryID(i *int) *ExpenseUpdateOne {
	if i != nil {
		euo.SetCategoryID(*i)
	}
	return euo
}

// ClearCategoryID clears the value of the "category_id" field.
func (euo *ExpenseUpdateOne) ClearCategoryID() *ExpenseUpdateOne {
	euo.mutation.ClearCategoryID()
	return euo
}

// SetCreatedAt sets the "created_at" field.
func (euo *ExpenseUpdateOne) SetCreatedAt(t time.Time) *ExpenseUpdateOne {
	euo.mutation.SetCreatedAt(t)
	return euo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (euo *ExpenseUpdateOne) SetNillableCreatedAt(t *time.Time) *ExpenseUpdateOne {
	if t != nil {
		euo.SetCreatedAt(*t)
	}
	return euo
}

// SetUser sets the "user" edge to the User entity.
func (euo *ExpenseUpdateOne) SetUser(u *User) *ExpenseUpdateOne {
	return euo.SetUserID(u.ID)
}

// SetCategoryRefID sets the "category_ref" edge to the Category entity by ID.
func (euo *ExpenseUpdateOne) SetCategoryRefID(id int) *ExpenseUpdateOne {
	euo.mutation.SetCategoryRefID(id)
	return euo
}

// SetNillableCategoryRefID sets the "category_ref" edge to the Category entity by ID if the given value is not nil.
func (euo *ExpenseUpdateOne) SetNillableCategoryRefID(id *int) *ExpenseUpdateOne {
	if id != nil {
		euo = euo.SetCategoryRefID(*id)
	}
	return euo
}

// SetCategoryRef sets the "category_ref" edge to the Category entity.
func (euo *ExpenseUpdateOne) SetCategoryRef(c *Category) *ExpenseUpdateOne {
	return euo.SetCategoryRefID(c.ID)
}

// Mutation returns the ExpenseMutation object of the builder.
func (euo *ExpenseUpdateOne) Mutation() *ExpenseMutation {
	return euo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (euo *ExpenseUpdateOne) ClearUser() *ExpenseUpdateOne {
	euo.mutation.ClearUser()
	return euo
}

// ClearCategoryRef clears the "category_ref" edge to the Category entity.
func (euo *ExpenseUpdateOne) ClearCategoryRef() *ExpenseUpdateOne {
	euo.mutation.ClearCategoryRef()
	return euo
}

// Where appends a list predicates to the ExpenseUpdate builder.
func (euo *ExpenseUpdateOne) Where(ps ...predicate.Expense) *ExpenseUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *ExpenseUpdateOne) Select(field string, fields ...string) *ExpenseUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Expense entity.
func (euo *ExpenseUpdateOne) Save(ctx context.Context) (*Expense, error) {
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *ExpenseUpdateOne) SaveX(ctx context.Context) *Expense {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *ExpenseUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *ExpenseUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *ExpenseUpdateOne) check() error {
	if v, ok := euo.mutation.Title(); ok {
		if err := expense.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Expense.title": %w`, err)}
		}
	}
	if euo.mutation.UserCleared() && len(euo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Expense.user"`)
	}
	return nil
}

func (euo *ExpenseUpdateOne) sqlSave(ctx context.Context) (_node *Expense, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(expense.Table, expense.Columns, sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Expense.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, expense.FieldID)
		for _, f := range fields {
			if !expense.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != expense.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.Title(); ok {
		_spec.SetField(expense.FieldTitle, field.TypeString, value)
	}
	if value, ok := euo.mutation.Amount(); ok {
		_spec.SetField(expense.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := euo.mutation.AddedAmount(); ok {
		_spec.AddField(expense.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := euo.mutation.Category(); ok {
		_spec.SetField(expense.FieldCategory, field.TypeString, value)
	}
	if euo.mutation.CategoryCleared() {
		_spec.ClearField(expense.FieldCategory, field.TypeString)
	}
	if value, ok := euo.mutation.CreatedAt(); ok {
		_spec.SetField(expense.FieldCreatedAt, field.TypeTime, value)
	}
	if euo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expense.UserTable,
			Columns: []string{expense.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expense.UserTable,
			Columns: []string{expense.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if euo.mutation.CategoryRefCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expense.CategoryRefTable,
			Columns: []string{expense.CategoryRefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.CategoryRefIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   expense.CategoryRefTable,
			Columns: []string{expense.CategoryRefColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Expense{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{expense.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
