// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"expense-server/ent/category"
	"expense-server/ent/recurringexpense"
	"expense-server/ent/user"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecurringExpenseCreate is the builder for creating a RecurringExpense entity.
type RecurringExpenseCreate struct {
	config
	mutation *RecurringExpenseMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (rec *RecurringExpenseCreate) SetUserID(i int) *RecurringExpenseCreate {
	rec.mutation.SetUserID(i)
	return rec
}

// SetTitle sets the "title" field.
func (rec *RecurringExpenseCreate) SetTitle(s string) *RecurringExpenseCreate {
	rec.mutation.SetTitle(s)
	return rec
}

// SetAmount sets the "amount" field.
func (rec *RecurringExpenseCreate) SetAmount(f float64) *RecurringExpenseCreate {
	rec.mutation.SetAmount(f)
	return rec
}

// SetCategoryID sets the "category_id" field.
func (rec *RecurringExpenseCreate) SetCategoryID(i int) *RecurringExpenseCreate {
	rec.mutation.SetCategoryID(i)
	return rec
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (rec *RecurringExpenseCreate) SetNillableCategoryID(i *int) *RecurringExpenseCreate {
	if i != nil {
		rec.SetCategoryID(*i)
	}
	return rec
}

// SetInterval sets the "interval" field.
func (rec *RecurringExpenseCreate) SetInterval(s string) *RecurringExpenseCreate {
	rec.mutation.SetInterval(s)
	return rec
}

// SetNextRunDate sets the "next_run_date" field.
func (rec *RecurringExpenseCreate) SetNextRunDate(t time.Time) *RecurringExpenseCreate {
	rec.mutation.SetNextRunDate(t)
	return rec
}

// SetLastRunDate sets the "last_run_date" field.
func (rec *RecurringExpenseCreate) SetLastRunDate(t time.Time) *RecurringExpenseCreate {
	rec.mutation.SetLastRunDate(t)
	return rec
}

// SetNillableLastRunDate sets the "last_run_date" field if the given value is not nil.
func (rec *RecurringExpenseCreate) SetNillableLastRunDate(t *time.Time) *RecurringExpenseCreate {
	if t != nil {
		rec.SetLastRunDate(*t)
	}
	return rec
}

// SetIsActive sets the "is_active" field.
func (rec *RecurringExpenseCreate) SetIsActive(b bool) *RecurringExpenseCreate {
	rec.mutation.SetIsActive(b)
	return rec
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (rec *RecurringExpenseCreate) SetNillableIsActive(b *bool) *RecurringExpenseCreate {
	if b != nil {
		rec.SetIsActive(*b)
	}
	return rec
}

// SetCreatedAt sets the "created_at" field.
func (rec *RecurringExpenseCreate) SetCreatedAt(t time.Time) *RecurringExpenseCreate {
	rec.mutation.SetCreatedAt(t)
	return rec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rec *RecurringExpenseCreate) SetNillableCreatedAt(t *time.Time) *RecurringExpenseCreate {
	if t != nil {
		rec.SetCreatedAt(*t)
	}
	return rec
}

// SetID sets the "id" field.
func (rec *RecurringExpenseCreate) SetID(i int) *RecurringExpenseCreate {
	rec.mutation.SetID(i)
	return rec
}

// SetUser sets the "user" edge to the User entity.
func (rec *RecurringExpenseCreate) SetUser(u *User) *RecurringExpenseCreate {
	return rec.SetUserID(u.ID)
}

// SetCategory sets the "category" edge to the Category entity.
func (rec *RecurringExpenseCreate) SetCategory(c *Category) *RecurringExpenseCreate {
	return rec.SetCategoryID(c.ID)
}

// Mutation returns the RecurringExpenseMutation object of the builder.
func (rec *RecurringExpenseCreate) Mutation() *RecurringExpenseMutation {
	return rec.mutation
}

// Save creates the RecurringExpense in the database.
func (rec *RecurringExpenseCreate) Save(ctx context.Context) (*RecurringExpense, error) {
	rec.defaults()
	return withHooks(ctx, rec.sqlSave, rec.mutation, rec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rec *RecurringExpenseCreate) SaveX(ctx context.Context) *RecurringExpense {
	v, err := rec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rec *RecurringExpenseCreate) Exec(ctx context.Context) error {
	_, err := rec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rec *RecurringExpenseCreate) ExecX(ctx context.Context) {
	if err := rec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rec *RecurringExpenseCreate) defaults() {
	if _, ok := rec.mutation.IsActive(); !ok {
		v := recurringexpense.DefaultIsActive
		rec.mutation.SetIsActive(v)
	}
	if _, ok := rec.mutation.CreatedAt(); !ok {
		v := recurringexpense.DefaultCreatedAt()
		rec.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rec *RecurringExpenseCreate) check() error {
	if _, ok := rec.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RecurringExpense.user_id"`)}
	}
	if _, ok := rec.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "RecurringExpense.title"`)}
	}
	if v, ok := rec.mutation.Title(); ok {
		if err := recurringexpense.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "RecurringExpense.title": %w`, err)}
		}
	}
	if _, ok := rec.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "RecurringExpense.amount"`)}
	}
	if _, ok := rec.mutation.Interval(); !ok {
		return &ValidationError{Name: "interval", err: errors.New(`ent: missing required field "RecurringExpense.interval"`)}
	}
	if _, ok := rec.mutation.NextRunDate(); !ok {
		return &ValidationError{Name: "next_run_date", err: errors.New(`ent: missing required field "RecurringExpense.next_run_date"`)}
	}
	if _, ok := rec.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "RecurringExpense.is_active"`)}
	}
	if len(rec.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RecurringExpense.user"`)}
	}
	return nil
}

func (rec *RecurringExpenseCreate) sqlSave(ctx context.Context) (*RecurringExpense, error) {
	if err := rec.check(); err != nil {
		return nil, err
	}
	_node, _spec := rec.createSpec()
	if err := sqlgraph.CreateNode(ctx, rec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	rec.mutation.id = &_node.ID
	rec.mutation.done = true
	return _node, nil
}

func (rec *RecurringExpenseCreate) createSpec() (*RecurringExpense, *sqlgraph.CreateSpec) {
	var (
		_node = &RecurringExpense{config: rec.config}
		_spec = sqlgraph.NewCreateSpec(recurringexpense.Table, sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt))
	)
	if id, ok := rec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := rec.mutation.Title(); ok {
		_spec.SetField(recurringexpense.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := rec.mutation.Amount(); ok {
		_spec.SetField(recurringexpense.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := rec.mutation.Interval(); ok {
		_spec.SetField(recurringexpense.FieldInterval, field.TypeString, value)
		_node.Interval = value
	}
	if value, ok := rec.mutation.NextRunDate(); ok {
		_spec.SetField(recurringexpense.FieldNextRunDate, field.TypeTime, value)
		_node.NextRunDate = value
	}
	if value, ok := rec.mutation.LastRunDate(); ok {
		_spec.SetField(recurringexpense.FieldLastRunDate, field.TypeTime, value)
		_node.LastRunDate = &value
	}
	if value, ok := rec.mutation.IsActive(); ok {
		_spec.SetField(recurringexpense.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := rec.mutation.CreatedAt(); ok {
		_spec.SetField(recurringexpense.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := rec.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.UserTable,
			Columns: []string{recurringexpense.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rec.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.CategoryTable,
			Columns: []string{recurringexpense.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CategoryID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RecurringExpenseCreateBulk is the builder for creating many RecurringExpense entities in bulk.
type RecurringExpenseCreateBulk struct {
	config
	err      error
	builders []*RecurringExpenseCreate
}

// Save creates the RecurringExpense entities in the database.
func (recb *RecurringExpenseCreateBulk) Save(ctx context.Context) ([]*RecurringExpense, error) {
	if recb.err != nil {
		return nil, recb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(recb.builders))
	nodes := make([]*RecurringExpense, len(recb.builders))
	mutators := make([]Mutator, len(recb.builders))
	for i := range recb.builders {
		func(i int, root context.Context) {
			builder := recb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RecurringExpenseMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, recb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, recb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, recb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (recb *RecurringExpenseCreateBulk) SaveX(ctx context.Context) []*RecurringExpense {
	v, err := recb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (recb *RecurringExpenseCreateBulk) Exec(ctx context.Context) error {
	_, err := recb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (recb *RecurringExpenseCreateBulk) ExecX(ctx context.Context) {
	if err := recb.Exec(ctx); err != nil {
		panic(err)
	}
}
