// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"expense-server/ent/predicate"
	"expense-server/ent/recurringexpense"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecurringExpenseDelete is the builder for deleting a RecurringExpense entity.
type RecurringExpenseDelete struct {
	config
	hooks    []Hook
	mutation *RecurringExpenseMutation
}

// Where appends a list predicates to the RecurringExpenseDelete builder.
func (red *RecurringExpenseDelete) Where(ps ...predicate.RecurringExpense) *RecurringExpenseDelete {
	red.mutation.Where(ps...)
	return red
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (red *RecurringExpenseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, red.sqlExec, red.mutation, red.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (red *RecurringExpenseDelete) ExecX(ctx context.Context) int {
	n, err := red.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (red *RecurringExpenseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(recurringexpense.Table, sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt))
	if ps := red.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, red.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	red.mutation.done = true
	return affected, err
}

// RecurringExpenseDeleteOne is the builder for deleting a single RecurringExpense entity.
type RecurringExpenseDeleteOne struct {
	red *RecurringExpenseDelete
}

// Where appends a list predicates to the RecurringExpenseDelete builder.
func (redo *RecurringExpenseDeleteOne) Where(ps ...predicate.RecurringExpense) *RecurringExpenseDeleteOne {
	redo.red.mutation.Where(ps...)
	return redo
}

// Exec executes the deletion query.
func (redo *RecurringExpenseDeleteOne) Exec(ctx context.Context) error {
	n, err := redo.red.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{recurringexpense.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (redo *RecurringExpenseDeleteOne) ExecX(ctx context.Context) {
	if err := redo.Exec(ctx); err != nil {
		panic(err)
	}
}
