// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"expense-server/ent/category"
	"expense-server/ent/predicate"
	"expense-server/ent/recurringexpense"
	"expense-server/ent/user"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecurringExpenseQuery is the builder for querying RecurringExpense entities.
type RecurringExpenseQuery struct {
	config
	ctx          *QueryContext
	order        []recurringexpense.OrderOption
	inters       []Interceptor
	predicates   []predicate.RecurringExpense
	withUser     *UserQuery
	withCategory *CategoryQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RecurringExpenseQuery builder.
func (req *RecurringExpenseQuery) Where(ps ...predicate.RecurringExpense) *RecurringExpenseQuery {
	req.predicates = append(req.predicates, ps...)
	return req
}

// Limit the number of records to be returned by this query.
func (req *RecurringExpenseQuery) Limit(limit int) *RecurringExpenseQuery {
	req.ctx.Limit = &limit
	return req
}

// Offset to start from.
func (req *RecurringExpenseQuery) Offset(offset int) *RecurringExpenseQuery {
	req.ctx.Offset = &offset
	return req
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (req *RecurringExpenseQuery) Unique(unique bool) *RecurringExpenseQuery {
	req.ctx.Unique = &unique
	return req
}

// Order specifies how the records should be ordered.
func (req *RecurringExpenseQuery) Order(o ...recurringexpense.OrderOption) *RecurringExpenseQuery {
	req.order = append(req.order, o...)
	return req
}

// QueryUser chains the current query on the "user" edge.
func (req *RecurringExpenseQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: req.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := req.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := req.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(recurringexpense.Table, recurringexpense.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, recurringexpense.UserTable, recurringexpense.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(req.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCategory chains the current query on the "category" edge.
func (req *RecurringExpenseQuery) QueryCategory() *CategoryQuery {
	query := (&CategoryClient{config: req.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := req.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := req.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(recurringexpense.Table, recurringexpense.FieldID, selector),
			sqlgraph.To(category.Table, category.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, recurringexpense.CategoryTable, recurringexpense.CategoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(req.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RecurringExpense entity from the query.
// Returns a *NotFoundError when no RecurringExpense was found.
func (req *RecurringExpenseQuery) First(ctx context.Context) (*RecurringExpense, error) {
	nodes, err := req.Limit(1).All(setContextOp(ctx, req.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{recurringexpense.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (req *RecurringExpenseQuery) FirstX(ctx context.Context) *RecurringExpense {
	node, err := req.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RecurringExpense ID from the query.
// Returns a *NotFoundError when no RecurringExpense ID was found.
func (req *RecurringExpenseQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = req.Limit(1).IDs(setContextOp(ctx, req.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{recurringexpense.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (req *RecurringExpenseQuery) FirstIDX(ctx context.Context) int {
	id, err := req.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RecurringExpense entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RecurringExpense entity is found.
// Returns a *NotFoundError when no RecurringExpense entities are found.
func (req *RecurringExpenseQuery) Only(ctx context.Context) (*RecurringExpense, error) {
	nodes, err := req.Limit(2).All(setContextOp(ctx, req.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{recurringexpense.Label}
	default:
		return nil, &NotSingularError{recurringexpense.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (req *RecurringExpenseQuery) OnlyX(ctx context.Context) *RecurringExpense {
	node, err := req.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RecurringExpense ID in the query.
// Returns a *NotSingularError when more than one RecurringExpense ID is found.
// Returns a *NotFoundError when no entities are found.
func (req *RecurringExpenseQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = req.Limit(2).IDs(setContextOp(ctx, req.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{recurringexpense.Label}
	default:
		err = &NotSingularError{recurringexpense.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (req *RecurringExpenseQuery) OnlyIDX(ctx context.Context) int {
	id, err := req.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RecurringExpenses.
func (req *RecurringExpenseQuery) All(ctx context.Context) ([]*RecurringExpense, error) {
	ctx = setContextOp(ctx, req.ctx, ent.OpQueryAll)
	if err := req.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RecurringExpense, *RecurringExpenseQuery]()
	return withInterceptors[[]*RecurringExpense](ctx, req, qr, req.inters)
}

// AllX is like All, but panics if an error occurs.
func (req *RecurringExpenseQuery) AllX(ctx context.Context) []*RecurringExpense {
	nodes, err := req.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RecurringExpense IDs.
func (req *RecurringExpenseQuery) IDs(ctx context.Context) (ids []int, err error) {
	if req.ctx.Unique == nil && req.path != nil {
		req.Unique(true)
	}
	ctx = setContextOp(ctx, req.ctx, ent.OpQueryIDs)
	if err = req.Select(recurringexpense.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (req *RecurringExpenseQuery) IDsX(ctx context.Context) []int {
	ids, err := req.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (req *RecurringExpenseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, req.ctx, ent.OpQueryCount)
	if err := req.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, req, querierCount[*RecurringExpenseQuery](), req.inters)
}

// CountX is like Count, but panics if an error occurs.
func (req *RecurringExpenseQuery) CountX(ctx context.Context) int {
	count, err := req.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (req *RecurringExpenseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, req.ctx, ent.OpQueryExist)
	switch _, err := req.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (req *RecurringExpenseQuery) ExistX(ctx context.Context) bool {
	exist, err := req.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RecurringExpenseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (req *RecurringExpenseQuery) Clone() *RecurringExpenseQuery {
	if req == nil {
		return nil
	}
	return &RecurringExpenseQuery{
		config:       req.config,
		ctx:          req.ctx.Clone(),
		order:        append([]recurringexpense.OrderOption{}, req.order...),
		inters:       append([]Interceptor{}, req.inters...),
		predicates:   append([]predicate.RecurringExpense{}, req.predicates...),
		withUser:     req.withUser.Clone(),
		withCategory: req.withCategory.Clone(),
		// clone intermediate query.
		sql:  req.sql.Clone(),
		path: req.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (req *RecurringExpenseQuery) WithUser(opts ...func(*UserQuery)) *RecurringExpenseQuery {
	query := (&UserClient{config: req.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	req.withUser = query
	return req
}

// WithCategory tells the query-builder to eager-load the nodes that are connected to
// the "category" edge. The optional arguments are used to configure the query builder of the edge.
func (req *RecurringExpenseQuery) WithCategory(opts ...func(*CategoryQuery)) *RecurringExpenseQuery {
	query := (&CategoryClient{config: req.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	req.withCategory = query
	return req
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RecurringExpense.Query().
//		GroupBy(recurringexpense.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (req *RecurringExpenseQuery) GroupBy(field string, fields ...string) *RecurringExpenseGroupBy {
	req.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RecurringExpenseGroupBy{build: req}
	grbuild.flds = &req.ctx.Fields
	grbuild.label = recurringexpense.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.RecurringExpense.Query().
//		Select(recurringexpense.FieldUserID).
//		Scan(ctx, &v)
func (req *RecurringExpenseQuery) Select(fields ...string) *RecurringExpenseSelect {
	req.ctx.Fields = append(req.ctx.Fields, fields...)
	sbuild := &RecurringExpenseSelect{RecurringExpenseQuery: req}
	sbuild.label = recurringexpense.Label
	sbuild.flds, sbuild.scan = &req.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RecurringExpenseSelect configured with the given aggregations.
func (req *RecurringExpenseQuery) Aggregate(fns ...AggregateFunc) *RecurringExpenseSelect {
	return req.Select().Aggregate(fns...)
}

func (req *RecurringExpenseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range req.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, req); err != nil {
				return err
			}
		}
	}
	for _, f := range req.ctx.Fields {
		if !recurringexpense.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if req.path != nil {
		prev, err := req.path(ctx)
		if err != nil {
			return err
		}
		req.sql = prev
	}
	return nil
}

func (req *RecurringExpenseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RecurringExpense, error) {
	var (
		nodes       = []*RecurringExpense{}
		_spec       = req.querySpec()
		loadedTypes = [2]bool{
			req.withUser != nil,
			req.withCategory != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RecurringExpense).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RecurringExpense{config: req.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, req.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := req.withUser; query != nil {
		if err := req.loadUser(ctx, query, nodes, nil,
			func(n *RecurringExpense, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := req.withCategory; query != nil {
		if err := req.loadCategory(ctx, query, nodes, nil,
			func(n *RecurringExpense, e *Category) { n.Edges.Category = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (req *RecurringExpenseQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*RecurringExpense, init func(*RecurringExpense), assign func(*RecurringExpense, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RecurringExpense)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (req *RecurringExpenseQuery) loadCategory(ctx context.Context, query *CategoryQuery, nodes []*RecurringExpense, init func(*RecurringExpense), assign func(*RecurringExpense, *Category)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*RecurringExpense)
	for i := range nodes {
		if nodes[i].CategoryID == nil {
			continue
		}
		fk := *nodes[i].CategoryID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(category.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "category_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (req *RecurringExpenseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := req.querySpec()
	_spec.Node.Columns = req.ctx.Fields
	if len(req.ctx.Fields) > 0 {
		_spec.Unique = req.ctx.Unique != nil && *req.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, req.driver, _spec)
}

func (req *RecurringExpenseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(recurringexpense.Table, recurringexpense.Columns, sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt))
	_spec.From = req.sql
	if unique := req.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if req.path != nil {
		_spec.Unique = true
	}
	if fields := req.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recurringexpense.FieldID)
		for i := range fields {
			if fields[i] != recurringexpense.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if req.withUser != nil {
			_spec.Node.AddColumnOnce(recurringexpense.FieldUserID)
		}
		if req.withCategory != nil {
			_spec.Node.AddColumnOnce(recurringexpense.FieldCategoryID)
		}
	}
	if ps := req.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := req.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := req.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := req.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (req *RecurringExpenseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(req.driver.Dialect())
	t1 := builder.Table(recurringexpense.Table)
	columns := req.ctx.Fields
	if len(columns) == 0 {
		columns = recurringexpense.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if req.sql != nil {
		selector = req.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if req.ctx.Unique != nil && *req.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range req.predicates {
		p(selector)
	}
	for _, p := range req.order {
		p(selector)
	}
	if offset := req.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := req.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RecurringExpenseGroupBy is the group-by builder for RecurringExpense entities.
type RecurringExpenseGroupBy struct {
	selector
	build *RecurringExpenseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (regb *RecurringExpenseGroupBy) Aggregate(fns ...AggregateFunc) *RecurringExpenseGroupBy {
	regb.fns = append(regb.fns, fns...)
	return regb
}

// Scan applies the selector query and scans the result into the given value.
func (regb *RecurringExpenseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, regb.build.ctx, ent.OpQueryGroupBy)
	if err := regb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RecurringExpenseQuery, *RecurringExpenseGroupBy](ctx, regb.build, regb, regb.build.inters, v)
}

func (regb *RecurringExpenseGroupBy) sqlScan(ctx context.Context, root *RecurringExpenseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(regb.fns))
	for _, fn := range regb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*regb.flds)+len(regb.fns))
		for _, f := range *regb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*regb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := regb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RecurringExpenseSelect is the builder for selecting fields of RecurringExpense entities.
type RecurringExpenseSelect struct {
	*RecurringExpenseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (res *RecurringExpenseSelect) Aggregate(fns ...AggregateFunc) *RecurringExpenseSelect {
	res.fns = append(res.fns, fns...)
	return res
}

// Scan applies the selector query and scans the result into the given value.
func (res *RecurringExpenseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, res.ctx, ent.OpQuerySelect)
	if err := res.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RecurringExpenseQuery, *RecurringExpenseSelect](ctx, res.RecurringExpenseQuery, res, res.inters, v)
}

func (res *RecurringExpenseSelect) sqlScan(ctx context.Context, root *RecurringExpenseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(res.fns))
	for _, fn := range res.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*res.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := res.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
