// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"expense-server/ent/category"
	"expense-server/ent/predicate"
	"expense-server/ent/recurringexpense"
	"expense-server/ent/user"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RecurringExpenseUpdate is the builder for updating RecurringExpense entities.
type RecurringExpenseUpdate struct {
	config
	hooks    []Hook
	mutation *RecurringExpenseMutation
}

// Where appends a list predicates to the RecurringExpenseUpdate builder.
func (reu *RecurringExpenseUpdate) Where(ps ...predicate.RecurringExpense) *RecurringExpenseUpdate {
	reu.mutation.Where(ps...)
	return reu
}

// SetUserID sets the "user_id" field.
func (reu *RecurringExpenseUpdate) SetUserID(i int) *RecurringExpenseUpdate {
	reu.mutation.SetUserID(i)
	return reu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (reu *RecurringExpenseUpdate) SetNillableUserID(i *int) *RecurringExpenseUpdate {
	if i != nil {
		reu.SetUserID(*i)
	}
	return reu
}

// SetTitle sets the "title" field.
func (reu *RecurringExpenseUpdate) SetTitle(s string) *RecurringExpenseUpdate {
	reu.mutation.SetTitle(s)
	return reu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (reu *RecurringExpenseUpdate) SetNillableTitle(s *string) *RecurringExpenseUpdate {
	if s != nil {
		reu.SetTitle(*s)
	}
	return reu
}

// SetAmount sets the "amount" field.
func (reu *RecurringExpenseUpdate) SetAmount(f float64) *RecurringExpenseUpdate {
	reu.mutation.ResetAmount()
	reu.mutation.SetAmount(f)
	return reu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (reu *RecurringExpenseUpdate) SetNillableAmount(f *float64) *RecurringExpenseUpdate {
	if f != nil {
		reu.SetAmount(*f)
	}
	return reu
}

// AddAmount adds f to the "amount" field.
func (reu *RecurringExpenseUpdate) AddAmount(f float64) *RecurringExpenseUpdate {
	reu.mutation.AddAmount(f)
	return reu
}

// SetCategoryID sets the "category_id" field.
func (reu *RecurringExpenseUpdate) SetCategoryID(i int) *RecurringExpenseUpdate {
	reu.mutation.SetCategoryID(i)
	return reu
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (reu *RecurringExpenseUpdate) SetNillableCategoryID(i *int) *RecurringExpenseUpdate {
	if i != nil {
		reu.SetCategoryID(*i)
	}
	return reu
}

// ClearCategoryID clears the value of the "category_id" field.
func (reu *RecurringExpenseUpdate) ClearCategoryID() *RecurringExpenseUpdate {
	reu.mutation.ClearCategoryID()
	return reu
}

// SetInterval sets the "interval" field.
func (reu *RecurringExpenseUpdate) SetInterval(s string) *RecurringExpenseUpdate {
	reu.mutation.SetInterval(s)
	return reu
}

// SetNillableInterval sets the "interval" field if the given value is not nil.
func (reu *RecurringExpenseUpdate) SetNillableInterval(s *string) *RecurringExpenseUpdate {
	if s != nil {
		reu.SetInterval(*s)
	}
	return reu
}

// SetNextRunDate sets the "next_run_date" field.
func (reu *RecurringExpenseUpdate) SetNextRunDate(t time.Time) *RecurringExpenseUpdate {
	reu.mutation.SetNextRunDate(t)
	return reu
}

// SetNillableNextRunDate sets the "next_run_date" field if the given value is not nil.
func (reu *RecurringExpenseUpdate) SetNillableNextRunDate(t *time.Time) *RecurringExpenseUpdate {
	if t != nil {
		reu.SetNextRunDate(*t)
	}
	return reu
}

// SetLastRunDate sets the "last_run_date" field.
func (reu *RecurringExpenseUpdate) SetLastRunDate(t time.Time) *RecurringExpenseUpdate {
	reu.mutation.SetLastRunDate(t)
	return reu
}

// SetNillableLastRunDate sets the "last_run_date" field if the given value is not nil.
func (reu *RecurringExpenseUpdate) SetNillableLastRunDate(t *time.Time) *RecurringExpenseUpdate {
	if t != nil {
		reu.SetLastRunDate(*t)
	}
	return reu
}

// ClearLastRunDate clears the value of the "last_run_date" field.
func (reu *RecurringExpenseUpdate) ClearLastRunDate() *RecurringExpenseUpdate {
	reu.mutation.ClearLastRunDate()
	return reu
}

// SetIsActive sets the "is_active" field.
func (reu *RecurringExpenseUpdate) SetIsActive(b bool) *RecurringExpenseUpdate {
	reu.mutation.SetIsActive(b)
	return reu
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (reu *RecurringExpenseUpdate) SetNillableIsActive(b *bool) *RecurringExpenseUpdate {
	if b != nil {
		reu.SetIsActive(*b)
	}
	return reu
}

// SetCreatedAt sets the "created_at" field.
func (reu *RecurringExpenseUpdate) SetCreatedAt(t time.Time) *RecurringExpenseUpdate {
	reu.mutation.SetCreatedAt(t)
	return reu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (reu *RecurringExpenseUpdate) SetNillableCreatedAt(t *time.Time) *RecurringExpenseUpdate {
	if t != nil {
		reu.SetCreatedAt(*t)
	}
	return reu
}

// SetUser sets the "user" edge to the User entity.
func (reu *RecurringExpenseUpdate) SetUser(u *User) *RecurringExpenseUpdate {
	return reu.SetUserID(u.ID)
}

// SetCategory sets the "category" edge to the Category entity.
func (reu *RecurringExpenseUpdate) SetCategory(c *Category) *RecurringExpenseUpdate {
	return reu.SetCategoryID(c.ID)
}

// Mutation returns the RecurringExpenseMutation object of the builder.
func (reu *RecurringExpenseUpdate) Mutation() *RecurringExpenseMutation {
	return reu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (reu *RecurringExpenseUpdate) ClearUser() *RecurringExpenseUpdate {
	reu.mutation.ClearUser()
	return reu
}

// ClearCategory clears the "category" edge to the Category entity.
func (reu *RecurringExpenseUpdate) ClearCategory() *RecurringExpenseUpdate {
	reu.mutation.ClearCategory()
	return reu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (reu *RecurringExpenseUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, reu.sqlSave, reu.mutation, reu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (reu *RecurringExpenseUpdate) SaveX(ctx context.Context) int {
	affected, err := reu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (reu *RecurringExpenseUpdate) Exec(ctx context.Context) error {
	_, err := reu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (reu *RecurringExpenseUpdate) ExecX(ctx context.Context) {
	if err := reu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (reu *RecurringExpenseUpdate) check() error {
	if v, ok := reu.mutation.Title(); ok {
		if err := recurringexpense.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "RecurringExpense.title": %w`, err)}
		}
	}
	if reu.mutation.UserCleared() && len(reu.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecurringExpense.user"`)
	}
	return nil
}

func (reu *RecurringExpenseUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := reu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(recurringexpense.Table, recurringexpense.Columns, sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt))
	if ps := reu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := reu.mutation.Title(); ok {
		_spec.SetField(recurringexpense.FieldTitle, field.TypeString, value)
	}
	if value, ok := reu.mutation.Amount(); ok {
		_spec.SetField(recurringexpense.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := reu.mutation.AddedAmount(); ok {
		_spec.AddField(recurringexpense.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := reu.mutation.Interval(); ok {
		_spec.SetField(recurringexpense.FieldInterval, field.TypeString, value)
	}
	if value, ok := reu.mutation.NextRunDate(); ok {
		_spec.SetField(recurringexpense.FieldNextRunDate, field.TypeTime, value)
	}
	if value, ok := reu.mutation.LastRunDate(); ok {
		_spec.SetField(recurringexpense.FieldLastRunDate, field.TypeTime, value)
	}
	if reu.mutation.LastRunDateCleared() {
		_spec.ClearField(recurringexpense.FieldLastRunDate, field.TypeTime)
	}
	if value, ok := reu.mutation.IsActive(); ok {
		_spec.SetField(recurringexpense.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := reu.mutation.CreatedAt(); ok {
		_spec.SetField(recurringexpense.FieldCreatedAt, field.TypeTime, value)
	}
	if reu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.UserTable,
			Columns: []string{recurringexpense.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := reu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.UserTable,
			Columns: []string{recurringexpense.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if reu.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.CategoryTable,
			Columns: []string{recurringexpense.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := reu.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.CategoryTable,
			Columns: []string{recurringexpense.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, reu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recurringexpense.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	reu.mutation.done = true
	return n, nil
}

// RecurringExpenseUpdateOne is the builder for updating a single RecurringExpense entity.
type RecurringExpenseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RecurringExpenseMutation
}

// SetUserID sets the "user_id" field.
func (reuo *RecurringExpenseUpdateOne) SetUserID(i int) *RecurringExpenseUpdateOne {
	reuo.mutation.SetUserID(i)
	return reuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (reuo *RecurringExpenseUpdateOne) SetNillableUserID(i *int) *RecurringExpenseUpdateOne {
	if i != nil {
		reuo.SetUserID(*i)
	}
	return reuo
}

// SetTitle sets the "title" field.
func (reuo *RecurringExpenseUpdateOne) SetTitle(s string) *RecurringExpenseUpdateOne {
	reuo.mutation.SetTitle(s)
	return reuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (reuo *RecurringExpenseUpdateOne) SetNillableTitle(s *string) *RecurringExpenseUpdateOne {
	if s != nil {
		reuo.SetTitle(*s)
	}
	return reuo
}

// SetAmount sets the "amount" field.
func (reuo *RecurringExpenseUpdateOne) SetAmount(f float64) *RecurringExpenseUpdateOne {
	reuo.mutation.ResetAmount()
	reuo.mutation.SetAmount(f)
	return reuo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (reuo *RecurringExpenseUpdateOne) SetNillableAmount(f *float64) *RecurringExpenseUpdateOne {
	if f != nil {
		reuo.SetAmount(*f)
	}
	return reuo
}

// AddAmount adds f to the "amount" field.
func (reuo *RecurringExpenseUpdateOne) AddAmount(f float64) *RecurringExpenseUpdateOne {
	reuo.mutation.AddAmount(f)
	return reuo
}

// SetCategoryID sets the "category_id" field.
func (reuo *RecurringExpenseUpdateOne) SetCategoryID(i int) *RecurringExpenseUpdateOne {
	reuo.mutation.SetCategoryID(i)
	return reuo
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (reuo *RecurringExpenseUpdateOne) SetNillableCategoryID(i *int) *RecurringExpenseUpdateOne {
	if i != nil {
		reuo.SetCategoryID(*i)
	}
	return reuo
}

// ClearCategoryID clears the value of the "category_id" field.
func (reuo *RecurringExpenseUpdateOne) ClearCategoryID() *RecurringExpenseUpdateOne {
	reuo.mutation.ClearCategoryID()
	return reuo
}

// SetInterval sets the "interval" field.
func (reuo *RecurringExpenseUpdateOne) SetInterval(s string) *RecurringExpenseUpdateOne {
	reuo.mutation.SetInterval(s)
	return reuo
}

// SetNillableInterval sets the "interval" field if the given value is not nil.
func (reuo *RecurringExpenseUpdateOne) SetNillableInterval(s *string) *RecurringExpenseUpdateOne {
	if s != nil {
		reuo.SetInterval(*s)
	}
	return reuo
}

// SetNextRunDate sets the "next_run_date" field.
func (reuo *RecurringExpenseUpdateOne) SetNextRunDate(t time.Time) *RecurringExpenseUpdateOne {
	reuo.mutation.SetNextRunDate(t)
	return reuo
}

// SetNillableNextRunDate sets the "next_run_date" field if the given value is not nil.
func (reuo *RecurringExpenseUpdateOne) SetNillableNextRunDate(t *time.Time) *RecurringExpenseUpdateOne {
	if t != nil {
		reuo.SetNextRunDate(*t)
	}
	return reuo
}

// SetLastRunDate sets the "last_run_date" field.
func (reuo *RecurringExpenseUpdateOne) SetLastRunDate(t time.Time) *RecurringExpenseUpdateOne {
	reuo.mutation.SetLastRunDate(t)
	return reuo
}

// SetNillableLastRunDate sets the "last_run_date" field if the given value is not nil.
func (reuo *RecurringExpenseUpdateOne) SetNillableLastRunDate(t *time.Time) *RecurringExpenseUpdateOne {
	if t != nil {
		reuo.SetLastRunDate(*t)
	}
	return reuo
}

// ClearLastRunDate clears the value of the "last_run_date" field.
func (reuo *RecurringExpenseUpdateOne) ClearLastRunDate() *RecurringExpenseUpdateOne {
	reuo.mutation.ClearLastRunDate()
	return reuo
}

// SetIsActive sets the "is_active" field.
func (reuo *RecurringExpenseUpdateOne) SetIsActive(b bool) *RecurringExpenseUpdateOne {
	reuo.mutation.SetIsActive(b)
	return reuo
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (reuo *RecurringExpenseUpdateOne) SetNillableIsActive(b *bool) *RecurringExpenseUpdateOne {
	if b != nil {
		reuo.SetIsActive(*b)
	}
	return reuo
}

// SetCreatedAt sets the "created_at" field.
func (reuo *RecurringExpenseUpdateOne) SetCreatedAt(t time.Time) *RecurringExpenseUpdateOne {
	reuo.mutation.SetCreatedAt(t)
	return reuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (reuo *RecurringExpenseUpdateOne) SetNillableCreatedAt(t *time.Time) *RecurringExpenseUpdateOne {
	if t != nil {
		reuo.SetCreatedAt(*t)
	}
	return reuo
}

// SetUser sets the "user" edge to the User entity.
func (reuo *RecurringExpenseUpdateOne) SetUser(u *User) *RecurringExpenseUpdateOne {
	return reuo.SetUserID(u.ID)
}

// SetCategory sets the "category" edge to the Category entity.
func (reuo *RecurringExpenseUpdateOne) SetCategory(c *Category) *RecurringExpenseUpdateOne {
	return reuo.SetCategoryID(c.ID)
}

// Mutation returns the RecurringExpenseMutation object of the builder.
func (reuo *RecurringExpenseUpdateOne) Mutation() *RecurringExpenseMutation {
	return reuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (reuo *RecurringExpenseUpdateOne) ClearUser() *RecurringExpenseUpdateOne {
	reuo.mutation.ClearUser()
	return reuo
}

// ClearCategory clears the "category" edge to the Category entity.
func (reuo *RecurringExpenseUpdateOne) ClearCategory() *RecurringExpenseUpdateOne {
	reuo.mutation.ClearCategory()
	return reuo
}

// Where appends a list predicates to the RecurringExpenseUpdate builder.
func (reuo *RecurringExpenseUpdateOne) Where(ps ...predicate.RecurringExpense) *RecurringExpenseUpdateOne {
	reuo.mutation.Where(ps...)
	return reuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (reuo *RecurringExpenseUpdateOne) Select(field string, fields ...string) *RecurringExpenseUpdateOne {
	reuo.fields = append([]string{field}, fields...)
	return reuo
}

// Save executes the query and returns the updated RecurringExpense entity.
func (reuo *RecurringExpenseUpdateOne) Save(ctx context.Context) (*RecurringExpense, error) {
	return withHooks(ctx, reuo.sqlSave, reuo.mutation, reuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (reuo *RecurringExpenseUpdateOne) SaveX(ctx context.Context) *RecurringExpense {
	node, err := reuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (reuo *RecurringExpenseUpdateOne) Exec(ctx context.Context) error {
	_, err := reuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (reuo *RecurringExpenseUpdateOne) ExecX(ctx context.Context) {
	if err := reuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (reuo *RecurringExpenseUpdateOne) check() error {
	if v, ok := reuo.mutation.Title(); ok {
		if err := recurringexpense.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "RecurringExpense.title": %w`, err)}
		}
	}
	if reuo.mutation.UserCleared() && len(reuo.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RecurringExpense.user"`)
	}
	return nil
}

func (reuo *RecurringExpenseUpdateOne) sqlSave(ctx context.Context) (_node *RecurringExpense, err error) {
	if err := reuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(recurringexpense.Table, recurringexpense.Columns, sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt))
	id, ok := reuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RecurringExpense.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := reuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, recurringexpense.FieldID)
		for _, f := range fields {
			if !recurringexpense.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != recurringexpense.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := reuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := reuo.mutation.Title(); ok {
		_spec.SetField(recurringexpense.FieldTitle, field.TypeString, value)
	}
	if value, ok := reuo.mutation.Amount(); ok {
		_spec.SetField(recurringexpense.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := reuo.mutation.AddedAmount(); ok {
		_spec.AddField(recurringexpense.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := reuo.mutation.Interval(); ok {
		_spec.SetField(recurringexpense.FieldInterval, field.TypeString, value)
	}
	if value, ok := reuo.mutation.NextRunDate(); ok {
		_spec.SetField(recurringexpense.FieldNextRunDate, field.TypeTime, value)
	}
	if value, ok := reuo.mutation.LastRunDate(); ok {
		_spec.SetField(recurringexpense.FieldLastRunDate, field.TypeTime, value)
	}
	if reuo.mutation.LastRunDateCleared() {
		_spec.ClearField(recurringexpense.FieldLastRunDate, field.TypeTime)
	}
	if value, ok := reuo.mutation.IsActive(); ok {
		_spec.SetField(recurringexpense.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := reuo.mutation.CreatedAt(); ok {
		_spec.SetField(recurringexpense.FieldCreatedAt, field.TypeTime, value)
	}
	if reuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.UserTable,
			Columns: []string{recurringexpense.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := reuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.UserTable,
			Columns: []string{recurringexpense.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if reuo.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.CategoryTable,
			Columns: []string{recurringexpense.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := reuo.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   recurringexpense.CategoryTable,
			Columns: []string{recurringexpense.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RecurringExpense{config: reuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, reuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{recurringexpense.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	reuo.mutation.done = true
	return _node, nil
}
