// Code generated by ent, DO NOT EDIT.

package ent

import (
	"expense-server/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"password_hash,omitempty"`
	// Email holds the value of the "email" field.
	Email *string `json:"email,omitempty"`
	// FirstName holds the value of the "first_name" field.
	FirstName *string `json:"first_name,omitempty"`
	// LastName holds the value of the "last_name" field.
	LastName *string `json:"last_name,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// Theme holds the value of the "theme" field.
	Theme string `json:"theme,omitempty"`
	// WeeklyStart holds the value of the "weekly_start" field.
	WeeklyStart string `json:"weekly_start,omitempty"`
	// MonthlyStartDay holds the value of the "monthly_start_day" field.
	MonthlyStartDay int `json:"monthly_start_day,omitempty"`
	// BudgetAlertThreshold holds the value of the "budget_alert_threshold" field.
	BudgetAlertThreshold float64 `json:"budget_alert_threshold,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Sessions holds the value of the sessions edge.
	Sessions []*Session `json:"sessions,omitempty"`
	// Categories holds the value of the categories edge.
	Categories []*Category `json:"categories,omitempty"`
	// Expenses holds the value of the expenses edge.
	Expenses []*Expense `json:"expenses,omitempty"`
	// Budgets holds the value of the budgets edge.
	Budgets []*Budget `json:"budgets,omitempty"`
	// RecurringExpenses holds the value of the recurring_expenses edge.
	RecurringExpenses []*RecurringExpense `json:"recurring_expenses,omitempty"`
	// ChatMessages holds the value of the chat_messages edge.
	ChatMessages []*ChatMessage `json:"chat_messages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// SessionsOrErr returns the Sessions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SessionsOrErr() ([]*Session, error) {
	if e.loadedTypes[0] {
		return e.Sessions, nil
	}
	return nil, &NotLoadedError{edge: "sessions"}
}

// CategoriesOrErr returns the Categories value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) CategoriesOrErr() ([]*Category, error) {
	if e.loadedTypes[1] {
		return e.Categories, nil
	}
	return nil, &NotLoadedError{edge: "categories"}
}

// ExpensesOrErr returns the Expenses value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ExpensesOrErr() ([]*Expense, error) {
	if e.loadedTypes[2] {
		return e.Expenses, nil
	}
	return nil, &NotLoadedError{edge: "expenses"}
}

// BudgetsOrErr returns the Budgets value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) BudgetsOrErr() ([]*Budget, error) {
	if e.loadedTypes[3] {
		return e.Budgets, nil
	}
	return nil, &NotLoadedError{edge: "budgets"}
}

// RecurringExpensesOrErr returns the RecurringExpenses value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) RecurringExpensesOrErr() ([]*RecurringExpense, error) {
	if e.loadedTypes[4] {
		return e.RecurringExpenses, nil
	}
	return nil, &NotLoadedError{edge: "recurring_expenses"}
}

// ChatMessagesOrErr returns the ChatMessages value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ChatMessagesOrErr() ([]*ChatMessage, error) {
	if e.loadedTypes[5] {
		return e.ChatMessages, nil
	}
	return nil, &NotLoadedError{edge: "chat_messages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldBudgetAlertThreshold:
			values[i] = new(sql.NullFloat64)
		case user.FieldID, user.FieldMonthlyStartDay:
			values[i] = new(sql.NullInt64)
		case user.FieldUsername, user.FieldPasswordHash, user.FieldEmail, user.FieldFirstName, user.FieldLastName, user.FieldCurrency, user.FieldTheme, user.FieldWeeklyStart:
			values[i] = new(sql.NullString)
		case user.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			u.ID = int(value.Int64)
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				u.Username = value.String
			}
		case user.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				u.PasswordHash = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				u.Email = new(string)
				*u.Email = value.String
			}
		case user.FieldFirstName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field first_name", values[i])
			} else if value.Valid {
				u.FirstName = new(string)
				*u.FirstName = value.String
			}
		case user.FieldLastName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name", values[i])
			} else if value.Valid {
				u.LastName = new(string)
				*u.LastName = value.String
			}
		case user.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				u.Currency = value.String
			}
		case user.FieldTheme:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field theme", values[i])
			} else if value.Valid {
				u.Theme = value.String
			}
		case user.FieldWeeklyStart:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field weekly_start", values[i])
			} else if value.Valid {
				u.WeeklyStart = value.String
			}
		case user.FieldMonthlyStartDay:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field monthly_start_day", values[i])
			} else if value.Valid {
				u.MonthlyStartDay = int(value.Int64)
			}
		case user.FieldBudgetAlertThreshold:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field budget_alert_threshold", values[i])
			} else if value.Valid {
				u.BudgetAlertThreshold = value.Float64
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				u.CreatedAt = value.Time
			}
		default:
			u.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (u *User) Value(name string) (ent.Value, error) {
	return u.selectValues.Get(name)
}

// QuerySessions queries the "sessions" edge of the User entity.
func (u *User) QuerySessions() *SessionQuery {
	return NewUserClient(u.config).QuerySessions(u)
}

// QueryCategories queries the "categories" edge of the User entity.
func (u *User) QueryCategories() *CategoryQuery {
	return NewUserClient(u.config).QueryCategories(u)
}

// QueryExpenses queries the "expenses" edge of the User entity.
func (u *User) QueryExpenses() *ExpenseQuery {
	return NewUserClient(u.config).QueryExpenses(u)
}

// QueryBudgets queries the "budgets" edge of the User entity.
func (u *User) QueryBudgets() *BudgetQuery {
	return NewUserClient(u.config).QueryBudgets(u)
}

// QueryRecurringExpenses queries the "recurring_expenses" edge of the User entity.
func (u *User) QueryRecurringExpenses() *RecurringExpenseQuery {
	return NewUserClient(u.config).QueryRecurringExpenses(u)
}

// QueryChatMessages queries the "chat_messages" edge of the User entity.
func (u *User) QueryChatMessages() *ChatMessageQuery {
	return NewUserClient(u.config).QueryChatMessages(u)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return NewUserClient(u.config).UpdateOne(u)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	_tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = _tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", u.ID))
	builder.WriteString("username=")
	builder.WriteString(u.Username)
	builder.WriteString(", ")
	builder.WriteString("password_hash=")
	builder.WriteString(u.PasswordHash)
	builder.WriteString(", ")
	if v := u.Email; v != nil {
		builder.WriteString("email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := u.FirstName; v != nil {
		builder.WriteString("first_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := u.LastName; v != nil {
		builder.WriteString("last_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(u.Currency)
	builder.WriteString(", ")
	builder.WriteString("theme=")
	builder.WriteString(u.Theme)
	builder.WriteString(", ")
	builder.WriteString("weekly_start=")
	builder.WriteString(u.WeeklyStart)
	builder.WriteString(", ")
	builder.WriteString("monthly_start_day=")
	builder.WriteString(fmt.Sprintf("%v", u.MonthlyStartDay))
	builder.WriteString(", ")
	builder.WriteString("budget_alert_threshold=")
	builder.WriteString(fmt.Sprintf("%v", u.BudgetAlertThreshold))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(u.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
