// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"expense-server/ent/budget"
	"expense-server/ent/category"
	"expense-server/ent/chatmessage"
	"expense-server/ent/expense"
	"expense-server/ent/recurringexpense"
	"expense-server/ent/session"
	"expense-server/ent/user"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (uc *UserCreate) SetUsername(s string) *UserCreate {
	uc.mutation.SetUsername(s)
	return uc
}

// SetPasswordHash sets the "password_hash" field.
func (uc *UserCreate) SetPasswordHash(s string) *UserCreate {
	uc.mutation.SetPasswordHash(s)
	return uc
}

// SetEmail sets the "email" field.
func (uc *UserCreate) SetEmail(s string) *UserCreate {
	uc.mutation.SetEmail(s)
	return uc
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (uc *UserCreate) SetNillableEmail(s *string) *UserCreate {
	if s != nil {
		uc.SetEmail(*s)
	}
	return uc
}

// SetFirstName sets the "first_name" field.
func (uc *UserCreate) SetFirstName(s string) *UserCreate {
	uc.mutation.SetFirstName(s)
	return uc
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (uc *UserCreate) SetNillableFirstName(s *string) *UserCreate {
	if s != nil {
		uc.SetFirstName(*s)
	}
	return uc
}

// SetLastName sets the "last_name" field.
func (uc *UserCreate) SetLastName(s string) *UserCreate {
	uc.mutation.SetLastName(s)
	return uc
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (uc *UserCreate) SetNillableLastName(s *string) *UserCreate {
	if s != nil {
		uc.SetLastName(*s)
	}
	return uc
}

// SetCurrency sets the "currency" field.
func (uc *UserCreate) SetCurrency(s string) *UserCreate {
	uc.mutation.SetCurrency(s)
	return uc
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (uc *UserCreate) SetNillableCurrency(s *string) *UserCreate {
	if s != nil {
		uc.SetCurrency(*s)
	}
	return uc
}

// SetTheme sets the "theme" field.
func (uc *UserCreate) SetTheme(s string) *UserCreate {
	uc.mutation.SetTheme(s)
	return uc
}

// SetNillableTheme sets the "theme" field if the given value is not nil.
func (uc *UserCreate) SetNillableTheme(s *string) *UserCreate {
	if s != nil {
		uc.SetTheme(*s)
	}
	return uc
}

// SetWeeklyStart sets the "weekly_start" field.
func (uc *UserCreate) SetWeeklyStart(s string) *UserCreate {
	uc.mutation.SetWeeklyStart(s)
	return uc
}

// SetNillableWeeklyStart sets the "weekly_start" field if the given value is not nil.
func (uc *UserCreate) SetNillableWeeklyStart(s *string) *UserCreate {
	if s != nil {
		uc.SetWeeklyStart(*s)
	}
	return uc
}

// SetMonthlyStartDay sets the "monthly_start_day" field.
func (uc *UserCreate) SetMonthlyStartDay(i int) *UserCreate {
	uc.mutation.SetMonthlyStartDay(i)
	return uc
}

// SetNillableMonthlyStartDay sets the "monthly_start_day" field if the given value is not nil.
func (uc *UserCreate) SetNillableMonthlyStartDay(i *int) *UserCreate {
	if i != nil {
		uc.SetMonthlyStartDay(*i)
	}
	return uc
}

// SetBudgetAlertThreshold sets the "budget_alert_threshold" field.
func (uc *UserCreate) SetBudgetAlertThreshold(f float64) *UserCreate {
	uc.mutation.SetBudgetAlertThreshold(f)
	return uc
}

// SetNillableBudgetAlertThreshold sets the "budget_alert_threshold" field if the given value is not nil.
func (uc *UserCreate) SetNillableBudgetAlertThreshold(f *float64) *UserCreate {
	if f != nil {
		uc.SetBudgetAlertThreshold(*f)
	}
	return uc
}

// SetCreatedAt sets the "created_at" field.
func (uc *UserCreate) SetCreatedAt(t time.Time) *UserCreate {
	uc.mutation.SetCreatedAt(t)
	return uc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (uc *UserCreate) SetNillableCreatedAt(t *time.Time) *UserCreate {
	if t != nil {
		uc.SetCreatedAt(*t)
	}
	return uc
}

// SetID sets the "id" field.
func (uc *UserCreate) SetID(i int) *UserCreate {
	uc.mutation.SetID(i)
	return uc
}

// AddSessionIDs adds the "sessions" edge to the Session entity by IDs.
func (uc *UserCreate) AddSessionIDs(ids ...string) *UserCreate {
	uc.mutation.AddSessionIDs(ids...)
	return uc
}

// AddSessions adds the "sessions" edges to the Session entity.
func (uc *UserCreate) AddSessions(s ...*Session) *UserCreate {
	ids := make([]string, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return uc.AddSessionIDs(ids...)
}

// AddCategoryIDs adds the "categories" edge to the Category entity by IDs.
func (uc *UserCreate) AddCategoryIDs(ids ...int) *UserCreate {
	uc.mutation.AddCategoryIDs(ids...)
	return uc
}

// AddCategories adds the "categories" edges to the Category entity.
func (uc *UserCreate) AddCategories(c ...*Category) *UserCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uc.AddCategoryIDs(ids...)
}

// AddExpenseIDs adds the "expenses" edge to the Expense entity by IDs.
func (uc *UserCreate) AddExpenseIDs(ids ...int) *UserCreate {
	uc.mutation.AddExpenseIDs(ids...)
	return uc
}

// AddExpenses adds the "expenses" edges to the Expense entity.
func (uc *UserCreate) AddExpenses(e ...*Expense) *UserCreate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return uc.AddExpenseIDs(ids...)
}

// AddBudgetIDs adds the "budgets" edge to the Budget entity by IDs.
func (uc *UserCreate) AddBudgetIDs(ids ...int) *UserCreate {
	uc.mutation.AddBudgetIDs(ids...)
	return uc
}

// AddBudgets adds the "budgets" edges to the Budget entity.
func (uc *UserCreate) AddBudgets(b ...*Budget) *UserCreate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uc.AddBudgetIDs(ids...)
}

// AddRecurringExpenseIDs adds the "recurring_expenses" edge to the RecurringExpense entity by IDs.
func (uc *UserCreate) AddRecurringExpenseIDs(ids ...int) *UserCreate {
	uc.mutation.AddRecurringExpenseIDs(ids...)
	return uc
}

// AddRecurringExpenses adds the "recurring_expenses" edges to the RecurringExpense entity.
func (uc *UserCreate) AddRecurringExpenses(r ...*RecurringExpense) *UserCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return uc.AddRecurringExpenseIDs(ids...)
}

// AddChatMessageIDs adds the "chat_messages" edge to the ChatMessage entity by IDs.
func (uc *UserCreate) AddChatMessageIDs(ids ...int) *UserCreate {
	uc.mutation.AddChatMessageIDs(ids...)
	return uc
}

// AddChatMessages adds the "chat_messages" edges to the ChatMessage entity.
func (uc *UserCreate) AddChatMessages(c ...*ChatMessage) *UserCreate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return uc.AddChatMessageIDs(ids...)
}

// Mutation returns the UserMutation object of the builder.
func (uc *UserCreate) Mutation() *UserMutation {
	return uc.mutation
}

// Save creates the User in the database.
func (uc *UserCreate) Save(ctx context.Context) (*User, error) {
	uc.defaults()
	return withHooks(ctx, uc.sqlSave, uc.mutation, uc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UserCreate) SaveX(ctx context.Context) *User {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (uc *UserCreate) Exec(ctx context.Context) error {
	_, err := uc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uc *UserCreate) ExecX(ctx context.Context) {
	if err := uc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (uc *UserCreate) defaults() {
	if _, ok := uc.mutation.Currency(); !ok {
		v := user.DefaultCurrency
		uc.mutation.SetCurrency(v)
	}
	if _, ok := uc.mutation.Theme(); !ok {
		v := user.DefaultTheme
		uc.mutation.SetTheme(v)
	}
	if _, ok := uc.mutation.WeeklyStart(); !ok {
		v := user.DefaultWeeklyStart
		uc.mutation.SetWeeklyStart(v)
	}
	if _, ok := uc.mutation.MonthlyStartDay(); !ok {
		v := user.DefaultMonthlyStartDay
		uc.mutation.SetMonthlyStartDay(v)
	}
	if _, ok := uc.mutation.BudgetAlertThreshold(); !ok {
		v := user.DefaultBudgetAlertThreshold
		uc.mutation.SetBudgetAlertThreshold(v)
	}
	if _, ok := uc.mutation.CreatedAt(); !ok {
		v := user.DefaultCreatedAt()
		uc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uc *UserCreate) check() error {
	if _, ok := uc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "User.username"`)}
	}
	if v, ok := uc.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if _, ok := uc.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "User.password_hash"`)}
	}
	if v, ok := uc.mutation.PasswordHash(); ok {
		if err := user.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "User.password_hash": %w`, err)}
		}
	}
	if _, ok := uc.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "User.currency"`)}
	}
	if _, ok := uc.mutation.Theme(); !ok {
		return &ValidationError{Name: "theme", err: errors.New(`ent: missing required field "User.theme"`)}
	}
	if _, ok := uc.mutation.WeeklyStart(); !ok {
		return &ValidationError{Name: "weekly_start", err: errors.New(`ent: missing required field "User.weekly_start"`)}
	}
	if _, ok := uc.mutation.MonthlyStartDay(); !ok {
		return &ValidationError{Name: "monthly_start_day", err: errors.New(`ent: missing required field "User.monthly_start_day"`)}
	}
	if _, ok := uc.mutation.BudgetAlertThreshold(); !ok {
		return &ValidationError{Name: "budget_alert_threshold", err: errors.New(`ent: missing required field "User.budget_alert_threshold"`)}
	}
	return nil
}

func (uc *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	if err := uc.check(); err != nil {
		return nil, err
	}
	_node, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	uc.mutation.id = &_node.ID
	uc.mutation.done = true
	return _node, nil
}

func (uc *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		_node = &User{config: uc.config}
		_spec = sqlgraph.NewCreateSpec(user.Table, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	)
	if id, ok := uc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := uc.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := uc.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := uc.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
		_node.Email = &value
	}
	if value, ok := uc.mutation.FirstName(); ok {
		_spec.SetField(user.FieldFirstName, field.TypeString, value)
		_node.FirstName = &value
	}
	if value, ok := uc.mutation.LastName(); ok {
		_spec.SetField(user.FieldLastName, field.TypeString, value)
		_node.LastName = &value
	}
	if value, ok := uc.mutation.Currency(); ok {
		_spec.SetField(user.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := uc.mutation.Theme(); ok {
		_spec.SetField(user.FieldTheme, field.TypeString, value)
		_node.Theme = value
	}
	if value, ok := uc.mutation.WeeklyStart(); ok {
		_spec.SetField(user.FieldWeeklyStart, field.TypeString, value)
		_node.WeeklyStart = value
	}
	if value, ok := uc.mutation.MonthlyStartDay(); ok {
		_spec.SetField(user.FieldMonthlyStartDay, field.TypeInt, value)
		_node.MonthlyStartDay = value
	}
	if value, ok := uc.mutation.BudgetAlertThreshold(); ok {
		_spec.SetField(user.FieldBudgetAlertThreshold, field.TypeFloat64, value)
		_node.BudgetAlertThreshold = value
	}
	if value, ok := uc.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := uc.mutation.SessionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.SessionsTable,
			Columns: []string{user.SessionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(session.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.CategoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.CategoriesTable,
			Columns: []string{user.CategoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(category.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.ExpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ExpensesTable,
			Columns: []string{user.ExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(expense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.BudgetsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.BudgetsTable,
			Columns: []string{user.BudgetsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(budget.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.RecurringExpensesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.RecurringExpensesTable,
			Columns: []string{user.RecurringExpensesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recurringexpense.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.ChatMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.ChatMessagesTable,
			Columns: []string{user.ChatMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserCreateBulk is the builder for creating many User entities in bulk.
type UserCreateBulk struct {
	config
	err      error
	builders []*UserCreate
}

// Save creates the User entities in the database.
func (ucb *UserCreateBulk) Save(ctx context.Context) ([]*User, error) {
	if ucb.err != nil {
		return nil, ucb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ucb.builders))
	nodes := make([]*User, len(ucb.builders))
	mutators := make([]Mutator, len(ucb.builders))
	for i := range ucb.builders {
		func(i int, root context.Context) {
			builder := ucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ucb *UserCreateBulk) SaveX(ctx context.Context) []*User {
	v, err := ucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ucb *UserCreateBulk) Exec(ctx context.Context) error {
	_, err := ucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ucb *UserCreateBulk) ExecX(ctx context.Context) {
	if err := ucb.Exec(ctx); err != nil {
		panic(err)
	}
}
