// Code generated by ent, DO NOT EDIT.

package recurringexpense

import (
	"expense-server/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldUserID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldTitle, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldAmount, v))
}

// CategoryID applies equality check predicate on the "category_id" field. It's identical to CategoryIDEQ.
func CategoryID(v int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldCategoryID, v))
}

// Interval applies equality check predicate on the "interval" field. It's identical to IntervalEQ.
func Interval(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldInterval, v))
}

// NextRunDate applies equality check predicate on the "next_run_date" field. It's identical to NextRunDateEQ.
func NextRunDate(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldNextRunDate, v))
}

// LastRunDate applies equality check predicate on the "last_run_date" field. It's identical to LastRunDateEQ.
func LastRunDate(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldLastRunDate, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldIsActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNotIn(FieldUserID, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldContainsFold(FieldTitle, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLTE(FieldAmount, v))
}

// CategoryIDEQ applies the EQ predicate on the "category_id" field.
func CategoryIDEQ(v int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldCategoryID, v))
}

// CategoryIDNEQ applies the NEQ predicate on the "category_id" field.
func CategoryIDNEQ(v int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNEQ(FieldCategoryID, v))
}

// CategoryIDIn applies the In predicate on the "category_id" field.
func CategoryIDIn(vs ...int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldIn(FieldCategoryID, vs...))
}

// CategoryIDNotIn applies the NotIn predicate on the "category_id" field.
func CategoryIDNotIn(vs ...int) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNotIn(FieldCategoryID, vs...))
}

// CategoryIDIsNil applies the IsNil predicate on the "category_id" field.
func CategoryIDIsNil() predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldIsNull(FieldCategoryID))
}

// CategoryIDNotNil applies the NotNil predicate on the "category_id" field.
func CategoryIDNotNil() predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNotNull(FieldCategoryID))
}

// IntervalEQ applies the EQ predicate on the "interval" field.
func IntervalEQ(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldInterval, v))
}

// IntervalNEQ applies the NEQ predicate on the "interval" field.
func IntervalNEQ(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNEQ(FieldInterval, v))
}

// IntervalIn applies the In predicate on the "interval" field.
func IntervalIn(vs ...string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldIn(FieldInterval, vs...))
}

// IntervalNotIn applies the NotIn predicate on the "interval" field.
func IntervalNotIn(vs ...string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNotIn(FieldInterval, vs...))
}

// IntervalGT applies the GT predicate on the "interval" field.
func IntervalGT(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGT(FieldInterval, v))
}

// IntervalGTE applies the GTE predicate on the "interval" field.
func IntervalGTE(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGTE(FieldInterval, v))
}

// IntervalLT applies the LT predicate on the "interval" field.
func IntervalLT(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLT(FieldInterval, v))
}

// IntervalLTE applies the LTE predicate on the "interval" field.
func IntervalLTE(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLTE(FieldInterval, v))
}

// IntervalContains applies the Contains predicate on the "interval" field.
func IntervalContains(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldContains(FieldInterval, v))
}

// IntervalHasPrefix applies the HasPrefix predicate on the "interval" field.
func IntervalHasPrefix(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldHasPrefix(FieldInterval, v))
}

// IntervalHasSuffix applies the HasSuffix predicate on the "interval" field.
func IntervalHasSuffix(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldHasSuffix(FieldInterval, v))
}

// IntervalEqualFold applies the EqualFold predicate on the "interval" field.
func IntervalEqualFold(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEqualFold(FieldInterval, v))
}

// IntervalContainsFold applies the ContainsFold predicate on the "interval" field.
func IntervalContainsFold(v string) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldContainsFold(FieldInterval, v))
}

// NextRunDateEQ applies the EQ predicate on the "next_run_date" field.
func NextRunDateEQ(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldNextRunDate, v))
}

// NextRunDateNEQ applies the NEQ predicate on the "next_run_date" field.
func NextRunDateNEQ(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNEQ(FieldNextRunDate, v))
}

// NextRunDateIn applies the In predicate on the "next_run_date" field.
func NextRunDateIn(vs ...time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldIn(FieldNextRunDate, vs...))
}

// NextRunDateNotIn applies the NotIn predicate on the "next_run_date" field.
func NextRunDateNotIn(vs ...time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNotIn(FieldNextRunDate, vs...))
}

// NextRunDateGT applies the GT predicate on the "next_run_date" field.
func NextRunDateGT(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGT(FieldNextRunDate, v))
}

// NextRunDateGTE applies the GTE predicate on the "next_run_date" field.
func NextRunDateGTE(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGTE(FieldNextRunDate, v))
}

// NextRunDateLT applies the LT predicate on the "next_run_date" field.
func NextRunDateLT(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLT(FieldNextRunDate, v))
}

// NextRunDateLTE applies the LTE predicate on the "next_run_date" field.
func NextRunDateLTE(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLTE(FieldNextRunDate, v))
}

// LastRunDateEQ applies the EQ predicate on the "last_run_date" field.
func LastRunDateEQ(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldLastRunDate, v))
}

// LastRunDateNEQ applies the NEQ predicate on the "last_run_date" field.
func LastRunDateNEQ(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNEQ(FieldLastRunDate, v))
}

// LastRunDateIn applies the In predicate on the "last_run_date" field.
func LastRunDateIn(vs ...time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldIn(FieldLastRunDate, vs...))
}

// LastRunDateNotIn applies the NotIn predicate on the "last_run_date" field.
func LastRunDateNotIn(vs ...time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNotIn(FieldLastRunDate, vs...))
}

// LastRunDateGT applies the GT predicate on the "last_run_date" field.
func LastRunDateGT(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGT(FieldLastRunDate, v))
}

// LastRunDateGTE applies the GTE predicate on the "last_run_date" field.
func LastRunDateGTE(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGTE(FieldLastRunDate, v))
}

// LastRunDateLT applies the LT predicate on the "last_run_date" field.
func LastRunDateLT(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLT(FieldLastRunDate, v))
}

// LastRunDateLTE applies the LTE predicate on the "last_run_date" field.
func LastRunDateLTE(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLTE(FieldLastRunDate, v))
}

// LastRunDateIsNil applies the IsNil predicate on the "last_run_date" field.
func LastRunDateIsNil() predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldIsNull(FieldLastRunDate))
}

// LastRunDateNotNil applies the NotNil predicate on the "last_run_date" field.
func LastRunDateNotNil() predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNotNull(FieldLastRunDate))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNEQ(FieldIsActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.RecurringExpense {
	return predicate.RecurringExpense(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.RecurringExpense {
	return predicate.RecurringExpense(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCategory applies the HasEdge predicate on the "category" edge.
func HasCategory() predicate.RecurringExpense {
	return predicate.RecurringExpense(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CategoryTable, CategoryColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCategoryWith applies the HasEdge predicate on the "category" edge with a given conditions (other predicates).
func HasCategoryWith(preds ...predicate.Category) predicate.RecurringExpense {
	return predicate.RecurringExpense(func(s *sql.Selector) {
		step := newCategoryStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RecurringExpense) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RecurringExpense) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RecurringExpense) predicate.RecurringExpense {
	return predicate.RecurringExpense(sql.NotPredicates(p))
}
